import { useApi, wrapApiCallNullable } from '../../api-utils';
import { getChat } from '../../autogenerated/chat/chat';

export const useChatsApi = () => {
    const api = getChat();

    return useApi({
        create: api.chatControllerCreateChatV1,
        list: api.chatControllerListChatsV1,
        get: wrapApiCallNullable(api.chatControllerGetChatV1),
        delete: api.chatControllerDeleteChatV1,
        addItems: api.chatControllerAddItemsToChatV1,
    });
};
