import { useVideosApi } from './videos';
import { useWorkflowsApi } from './workflows';
import { useStorageApi } from './storage';
import { useStacksApi } from './stacks';
import { usePosesApi } from './poses';
import { useImagesApi } from './images';
import { useOperationsApi } from './operations';
import { getHautechAPI } from '../../autogenerated';

export const hautechApi = getHautechAPI();

export default {
    videos: useVideosApi(hautechApi),
    workflows: useWorkflowsApi(hautechApi),
    storage: useStorageApi(hautechApi),
    stacks: useStacksApi(hautechApi),
    poses: usePosesApi(hautechApi),
    images: useImagesApi(hautechApi),
    operations: useOperationsApi(hautechApi),
};
