import { useVideosApi } from './videos';
import { useWorkflowsApi } from './workflows';
import { useStorageApi } from './storage';
import { useStacksApi } from './stacks';
import { usePosesApi } from './poses';
import { useImagesApi } from './images';
import { useOperationsApi } from './operations';
import { useGroupsApi } from './groups';
import { getHautechAPI } from '../../autogenerated';
import { useAccountsApi } from './accounts';
import { useCollectionsApi } from './collections';
import { useBalancesApi } from './balances';
import { useAccessApi } from './access';

export const hautechApi = getHautechAPI();

export default {
    videos: useVideosApi(hautechApi),
    workflows: useWorkflowsApi(hautechApi),
    storage: useStorageApi(hautechApi),
    stacks: useStacksApi(hautechApi),
    poses: usePosesApi(hautechApi),
    images: useImagesApi(hautechApi),
    operations: useOperationsApi(hautechApi),
    groups: useGroupsApi(hautechApi),
    accounts: useAccountsApi(hautechApi),
    collections: useCollectionsApi(hautechApi),
    balances: useBalancesApi(hautechApi),
    access: useAccessApi(hautechApi),
};
