import { useApi, wrapApiCallNullable } from '../../api-utils';
import { getStacks } from '../../autogenerated/stacks/stacks';

export const useStacksApi = () => {
    const hautechApi = getStacks();

    return useApi({
        create: hautechApi.stacksControllerCreateStackV1,
        list: hautechApi.stacksControllerListStacksV1,
        get: wrapApiCallNullable(hautechApi.stacksControllerGetStackV1),
        updateMetadata: hautechApi.stacksControllerUpdateMetadataV1,
        items: {
            add: hautechApi.stacksControllerAddItemsV1,
            remove: hautechApi.stacksControllerRemoveItemsV1,
        },
    });
};
