import { defineConfig } from 'orval';

const CORE_API_URL = process.env.API_CORE_URL || 'https://api.hautech.ai';
const DIRECTORY_API_URL = process.env.API_DIRECTORY_URL || 'https://api-directory.hautech.ai';

export default defineConfig({
    api: {
        input: `${CORE_API_URL}/swagger.json`,
        output: {
            target: './src/autogenerated/index.ts',
            schemas: './src/autogenerated/schemas',
            client: 'axios',
            prettier: true,
            optionsParamRequired: false,
            allParamsOptional: false,
            urlEncodeParameters: true,
            mode: 'tags-split',
            override: {
                transformer: (output) => output,
                mutator: {
                    name: 'axiosMutator',
                    path: './src/api-utils.ts',
                },
            },
        },
    },
    directoryApi: {
        input: `${DIRECTORY_API_URL}/swagger-api-json`,
        output: {
            target: './src/autogenerated/directory/index.ts',
            schemas: './src/autogenerated/directory/schemas',
            client: 'axios',
            prettier: true,
            optionsParamRequired: false,
            allParamsOptional: false,
            urlEncodeParameters: true,
            mode: 'tags-split',
            override: {
                transformer: (output) => output,
                mutator: {
                    name: 'axiosMutator',
                    path: './src/api-utils.ts',
                },
            },
        },
    },
});
