import { AxiosResponse } from 'axios';
import createOperationUpdater from './updater';
import {
    GenerateV1Input,
    GenerateV3Input,
    GPTV1Input,
    ImagineV1Input,
    InpaintV1Input,
    ObjectDetectionV1Input,
    OperationEntity,
    OperationsApi,
    PoseEstimationV1Input,
    SegmentAnythingEmbeddingsV1Input,
    UpscaleV1Input,
} from '../../autogenerated';
import { ListProps, SDKOptions } from '../../types';
import { useAutogeneratedAPI } from '../api';

const operations = (options: SDKOptions) => {
    const api = useAutogeneratedAPI({ API: OperationsApi, options });
    const updates = createOperationUpdater(options);

    const createOperation =
        <T>(
            callMethod: (
                methods: OperationsApi,
                props: { input: T; metadata?: any },
            ) => Promise<AxiosResponse<OperationEntity, any>>,
        ) =>
        (props: { input: T; metadata?: any }) =>
            api.call({ run: (methods: OperationsApi) => callMethod(methods, props) });

    return {
        create: {
            detect: {
                v1: createOperation<ObjectDetectionV1Input>((methods, props) =>
                    methods.operationsControllerRunObjectDetectionV1V1(props),
                ),
            },
            estimatePose: {
                v1: createOperation<PoseEstimationV1Input>((methods, props) =>
                    methods.operationsControllerRunPoseEstimationV1V1(props),
                ),
            },
            generate: {
                v1: createOperation<GenerateV1Input>((methods, props) =>
                    methods.operationsControllerRunGenerateV1V1(props),
                ),
                v3: createOperation<GenerateV3Input>((methods, props) =>
                    methods.operationsControllerRunGenerateV3V1(props),
                ),
            },
            gpt: {
                v1: createOperation<GPTV1Input>((methods, props) => methods.operationsControllerRunGptV1V1(props)),
            },
            imagine: {
                v1: createOperation<ImagineV1Input>((methods, props) =>
                    methods.operationsControllerRunImagineV1V1(props),
                ),
            },
            inpaint: {
                v1: createOperation<InpaintV1Input>((methods, props) =>
                    methods.operationsControllerRunInpaintV1V1(props),
                ),
            },
            segmentEmbeddings: {
                v1: createOperation<SegmentAnythingEmbeddingsV1Input>((methods, props) =>
                    methods.operationsControllerRunSegmentAnythingEmbeddingsV1V1(props),
                ),
            },
            upscale: {
                v1: createOperation<UpscaleV1Input>((methods, props) =>
                    methods.operationsControllerRunUpscaleV1V1(props),
                ),
            },
        },
        get: (props: { id: string }) =>
            api.callWithReturningUndefinedOn404({
                run: (methods) => methods.operationsControllerGetOperationV1(props.id),
            }),
        getMany: (props: { ids: string[] }) =>
            api.call({
                run: (methods) => methods.operationsControllerGetOperationsV1({ ids: props.ids }),
            }),
        list: (props: ListProps = {}) =>
            api.call({
                run: (methods) =>
                    methods.operationsControllerListOperationsV1(props.orderBy, props.limit, props.cursor),
            }),
        updateMetadata: async (props: { id: string; metadata?: any }) =>
            api.call({
                run: (methods) => methods.operationsControllerUpdateMetadataV1(props.id, { overwrite: props.metadata }),
            }),
        updates,
        wait: async (props: { id: string; timeoutInSeconds?: number }) =>
            new Promise((resolve, reject) => {
                const initialDelay = 5000;
                const delay = 2000;

                const listenToOperation = (operation: { id: string }) => {
                    if (operation.id === props.id) {
                        clearTimeout(timeoutId);
                        resolve(operation);
                        updates.unsubscribe({ callback: listenToOperation });
                    }
                };
                updates.subscribe({ callback: listenToOperation });

                let timeoutId: NodeJS.Timeout;
                const poll = async () => {
                    const operation = await api.call({
                        run: (methods) => methods.operationsControllerGetOperationV1(props.id),
                    });
                    if (operation.status !== 'pending') return resolve(operation);
                    timeoutId = setTimeout(poll, delay);
                    updates.unsubscribe({ callback: listenToOperation });
                };
                timeoutId = setTimeout(poll, initialDelay);
            }),
    };
};

export default operations;
