/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type {
  AddBalanceControllerParamsDto,
  BalanceResultDto
} from '.././schemas';

import { axiosMutator } from '../../api-utils';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getBalances = () => {
const balancesControllerAddBalanceV1 = (
    id: string,
    addBalanceControllerParamsDto: AddBalanceControllerParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/accounts/${id}/balance`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: addBalanceControllerParamsDto
    },
      options);
    }
  const balancesControllerGetBalanceV1 = (
    id: string,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<BalanceResultDto>(
      {url: `/v1/accounts/${id}/balance`, method: 'GET'
    },
      options);
    }
  const balancesControllerGetBalanceForSelfV1 = (
    
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<BalanceResultDto>(
      {url: `/v1/accounts/self/balance`, method: 'GET'
    },
      options);
    }
  return {balancesControllerAddBalanceV1,balancesControllerGetBalanceV1,balancesControllerGetBalanceForSelfV1}};
export type BalancesControllerAddBalanceV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getBalances>['balancesControllerAddBalanceV1']>>>
export type BalancesControllerGetBalanceV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getBalances>['balancesControllerGetBalanceV1']>>>
export type BalancesControllerGetBalanceForSelfV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getBalances>['balancesControllerGetBalanceForSelfV1']>>>
