/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type {
  AccessControllerListSharedV1Params,
  AttachAccessControllerParamsDto,
  DetachAccessControllerParamsDto,
  GrantAccessControllerParams,
  ListAccessControllerDto,
  ListSharedResourcesResponseDto,
  RevokeAccessControllerParamsDto,
  ShareWithEveryoneControllerParamsDto
} from '.././schemas';

import { axiosMutator } from '../../api-utils';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAccess = () => {
const accessControllerGrantAccessV1 = (
    id: string,
    grantAccessControllerParams: GrantAccessControllerParams,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/resources/${id}/access/grant`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: grantAccessControllerParams
    },
      options);
    }
  const accessControllerRevokeAccessV1 = (
    id: string,
    revokeAccessControllerParamsDto: RevokeAccessControllerParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/resources/${id}/access/revoke`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: revokeAccessControllerParamsDto
    },
      options);
    }
  const accessControllerAttachAccessV1 = (
    id: string,
    attachAccessControllerParamsDto: AttachAccessControllerParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/resources/${id}/access/attach`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: attachAccessControllerParamsDto
    },
      options);
    }
  const accessControllerDetachAccessV1 = (
    id: string,
    detachAccessControllerParamsDto: DetachAccessControllerParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/resources/${id}/access/detach`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: detachAccessControllerParamsDto
    },
      options);
    }
  const accessControllerGrantAccessToEveryoneV1 = (
    id: string,
    shareWithEveryoneControllerParamsDto: ShareWithEveryoneControllerParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/resources/${id}/access/grant/everyone`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: shareWithEveryoneControllerParamsDto
    },
      options);
    }
  const accessControllerRevokeAccessFromEveryoneV1 = (
    id: string,
    shareWithEveryoneControllerParamsDto: ShareWithEveryoneControllerParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/resources/${id}/access/revoke/everyone`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: shareWithEveryoneControllerParamsDto
    },
      options);
    }
  /**
 * @summary UNSTABLE
 */
const accessControllerAccessV1 = (
    id: string,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<ListAccessControllerDto>(
      {url: `/v1/resources/${id}/access`, method: 'GET'
    },
      options);
    }
  /**
 * @summary List resources shared with current user
 */
const accessControllerListSharedV1 = (
    params?: AccessControllerListSharedV1Params,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<ListSharedResourcesResponseDto>(
      {url: `/v1/access/shared`, method: 'GET',
        params
    },
      options);
    }
  return {accessControllerGrantAccessV1,accessControllerRevokeAccessV1,accessControllerAttachAccessV1,accessControllerDetachAccessV1,accessControllerGrantAccessToEveryoneV1,accessControllerRevokeAccessFromEveryoneV1,accessControllerAccessV1,accessControllerListSharedV1}};
export type AccessControllerGrantAccessV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccess>['accessControllerGrantAccessV1']>>>
export type AccessControllerRevokeAccessV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccess>['accessControllerRevokeAccessV1']>>>
export type AccessControllerAttachAccessV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccess>['accessControllerAttachAccessV1']>>>
export type AccessControllerDetachAccessV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccess>['accessControllerDetachAccessV1']>>>
export type AccessControllerGrantAccessToEveryoneV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccess>['accessControllerGrantAccessToEveryoneV1']>>>
export type AccessControllerRevokeAccessFromEveryoneV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccess>['accessControllerRevokeAccessFromEveryoneV1']>>>
export type AccessControllerAccessV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccess>['accessControllerAccessV1']>>>
export type AccessControllerListSharedV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccess>['accessControllerListSharedV1']>>>
