// WebSocket Event Type Definitions

import { OperationEntity, PipelineDto, StackEntity } from '../autogenerated/schemas';

export interface BaseWsEvent<T> {
    timestamp: string;
    data: T;
}

export interface WsEventMap {
    'operation:created': BaseWsEvent<OperationEntity>;
    'operation:updated': BaseWsEvent<OperationEntity>;
    'pipeline:created': BaseWsEvent<PipelineDto>;
    'pipeline:updated': BaseWsEvent<PipelineDto>;
}
