// WebSocket Event Type Definitions

import { OperationEntity } from '../autogenerated/schemas';

export interface BaseWsEvent<T> {
    timestamp: string;
    data: T;
}

export interface OperationEvent extends BaseWsEvent<OperationEntity> {}

export interface WsEventMap {
    'operation:created': OperationEvent;
    'operation:updated': OperationEvent;
}
