/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type {
  ListLorasDto,
  LoraControllerListV1Params,
  LoraDto,
  LoraWebhookDto,
  StartFluxTrainingParamsDto,
  StartNaomiTrainingParamsDto,
  StartTrainingParamsDto
} from '.././schemas';

import { axiosMutator } from '../../api-utils';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getLora = () => {
const loraControllerStartFluxV1 = (
    startFluxTrainingParamsDto: StartFluxTrainingParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<LoraDto>(
      {url: `/v1/lora/train/flux`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startFluxTrainingParamsDto
    },
      options);
    }
  const loraControllerStartNaomiV1 = (
    startNaomiTrainingParamsDto: StartNaomiTrainingParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<LoraDto>(
      {url: `/v1/lora/train/naomi`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startNaomiTrainingParamsDto
    },
      options);
    }
  const loraControllerStartGeneralV1 = (
    startTrainingParamsDto: StartTrainingParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<LoraDto>(
      {url: `/v1/lora/train`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startTrainingParamsDto
    },
      options);
    }
  const loraControllerListV1 = (
    params?: LoraControllerListV1Params,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<ListLorasDto>(
      {url: `/v1/lora`, method: 'GET',
        params
    },
      options);
    }
  const loraControllerGetV1 = (
    id: string,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<LoraDto>(
      {url: `/v1/lora/${id}`, method: 'GET'
    },
      options);
    }
  const loraControllerTrainingsWebhookV1 = (
    loraWebhookDto: LoraWebhookDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/lora/trainings/webhook`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loraWebhookDto
    },
      options);
    }
  return {loraControllerStartFluxV1,loraControllerStartNaomiV1,loraControllerStartGeneralV1,loraControllerListV1,loraControllerGetV1,loraControllerTrainingsWebhookV1}};
export type LoraControllerStartFluxV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLora>['loraControllerStartFluxV1']>>>
export type LoraControllerStartNaomiV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLora>['loraControllerStartNaomiV1']>>>
export type LoraControllerStartGeneralV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLora>['loraControllerStartGeneralV1']>>>
export type LoraControllerListV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLora>['loraControllerListV1']>>>
export type LoraControllerGetV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLora>['loraControllerGetV1']>>>
export type LoraControllerTrainingsWebhookV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLora>['loraControllerTrainingsWebhookV1']>>>
