/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type {
  ListLorasDto,
  LoraControllerListV1Params,
  LoraDto,
  LoraWebhookDto,
  StartLoraTrainingParamsDto
} from '.././schemas';

import { axiosMutator } from '../../api-utils';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getLora = () => {
const loraControllerStartV1 = (
    startLoraTrainingParamsDto: StartLoraTrainingParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<LoraDto>(
      {url: `/v1/lora/train`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startLoraTrainingParamsDto
    },
      options);
    }
  const loraControllerListV1 = (
    params?: LoraControllerListV1Params,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<ListLorasDto>(
      {url: `/v1/lora`, method: 'GET',
        params
    },
      options);
    }
  const loraControllerGetV1 = (
    id: string,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<LoraDto>(
      {url: `/v1/lora/${id}`, method: 'GET'
    },
      options);
    }
  const loraControllerTrainingsWebhookV1 = (
    loraWebhookDto: LoraWebhookDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/lora/trainings/webhook`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loraWebhookDto
    },
      options);
    }
  return {loraControllerStartV1,loraControllerListV1,loraControllerGetV1,loraControllerTrainingsWebhookV1}};
export type LoraControllerStartV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLora>['loraControllerStartV1']>>>
export type LoraControllerListV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLora>['loraControllerListV1']>>>
export type LoraControllerGetV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLora>['loraControllerGetV1']>>>
export type LoraControllerTrainingsWebhookV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getLora>['loraControllerTrainingsWebhookV1']>>>
