import { MethodsPermissions } from '../autogenerated/permissions';

export const defaultPermissions: MethodsPermissions = {
    accounts: { create: false, list: false, read: false },
    balances: { read: true, self: { read: true, update: false }, update: false },
    collections: {
        create: true,
        items: { add: true, read: true, remove: true },
        metadata: { update: true },
        read: true,
    },
    groups: { accounts: { add: false, read: true, remove: false }, create: false, delete: false, read: true },
    images: { create: true, read: true },
    operations: { create: true, read: true, metadata: { update: true } },
    pipelines: { create: true, read: true },
    poses: { create: true, read: true, update: true },
    resources: {
        access: {
            attach: true,
            detach: true,
            grant: true,
            read: true,
            revoke: true,
        },
    },
    stacks: { create: true, items: { add: true, remove: true }, read: true, metadata: { update: true } },
    storage: { create: true, delete: true, read: true, update: true },
};
