/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type {
  AccountEntity,
  AccountsControllerListAccountsV1Params,
  CreateAccountParamsDto,
  ListAccountsDto,
  SelfAccountDto,
  UpdateAccountControllerParamsDto
} from '.././schemas';

import { axiosMutator } from '../../api-utils';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAccounts = () => {
const accountsControllerCreateAccountV1 = (
    createAccountParamsDto: CreateAccountParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<AccountEntity>(
      {url: `/v1/accounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccountParamsDto
    },
      options);
    }
  const accountsControllerListAccountsV1 = (
    params?: AccountsControllerListAccountsV1Params,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<ListAccountsDto>(
      {url: `/v1/accounts`, method: 'GET',
        params
    },
      options);
    }
  const accountsControllerGetSelfV1 = (
    
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<SelfAccountDto>(
      {url: `/v1/accounts/self`, method: 'GET'
    },
      options);
    }
  const accountsControllerGetAccountV1 = (
    id: string,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<AccountEntity>(
      {url: `/v1/accounts/${id}`, method: 'GET'
    },
      options);
    }
  const accountsControllerUpdateAccountV1 = (
    id: string,
    updateAccountControllerParamsDto: UpdateAccountControllerParamsDto,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<AccountEntity>(
      {url: `/v1/accounts/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateAccountControllerParamsDto
    },
      options);
    }
  const accountsControllerGetAccountByAliasV1 = (
    id: string,
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<AccountEntity>(
      {url: `/v1/accounts/alias/${id}`, method: 'GET'
    },
      options);
    }
  return {accountsControllerCreateAccountV1,accountsControllerListAccountsV1,accountsControllerGetSelfV1,accountsControllerGetAccountV1,accountsControllerUpdateAccountV1,accountsControllerGetAccountByAliasV1}};
export type AccountsControllerCreateAccountV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccounts>['accountsControllerCreateAccountV1']>>>
export type AccountsControllerListAccountsV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccounts>['accountsControllerListAccountsV1']>>>
export type AccountsControllerGetSelfV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccounts>['accountsControllerGetSelfV1']>>>
export type AccountsControllerGetAccountV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccounts>['accountsControllerGetAccountV1']>>>
export type AccountsControllerUpdateAccountV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccounts>['accountsControllerUpdateAccountV1']>>>
export type AccountsControllerGetAccountByAliasV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccounts>['accountsControllerGetAccountByAliasV1']>>>
