/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AccountsControllerListAccountsV1OrderBy = typeof AccountsControllerListAccountsV1OrderBy[keyof typeof AccountsControllerListAccountsV1OrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountsControllerListAccountsV1OrderBy = {
  createdAt_ASC: 'createdAt_ASC',
  createdAt_DESC: 'createdAt_DESC',
} as const;
