/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Decimal } from './decimal';
import type { AccountEntityType } from './accountEntityType';

export interface AccountEntity {
  id: string;
  balance: Decimal;
  createdAt: string;
  alias?: string;
  type: AccountEntityType;
}
