/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AccountEntityType } from './accountEntityType';
import type { Decimal } from './decimal';

export interface AccountEntity {
  id: string;
  balance: Decimal;
  createdAt: string;
  alias?: string;
  type: AccountEntityType;
}
