/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AccountsControllerListAccountsV1OrderBy = typeof AccountsControllerListAccountsV1OrderBy[keyof typeof AccountsControllerListAccountsV1OrderBy];


export const AccountsControllerListAccountsV1OrderBy = {
  createdAt_ASC: 'createdAt_ASC',
  createdAt_DESC: 'createdAt_DESC',
} as const;
