/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AddAccountToGroupParamsDtoRole = typeof AddAccountToGroupParamsDtoRole[keyof typeof AddAccountToGroupParamsDtoRole];


export const AddAccountToGroupParamsDtoRole = {
  maintainer: 'maintainer',
  member: 'member',
  owner: 'owner',
} as const;
