/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AlphabakeVtonV1ResponseKind } from './alphabakeVtonV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { AlphabakeVtonV1ResponseInput } from './alphabakeVtonV1ResponseInput';
import type { AlphabakeVtonV1ResponseStatus } from './alphabakeVtonV1ResponseStatus';
import type { AlphabakeVtonV1ResponseMetadata } from './alphabakeVtonV1ResponseMetadata';

export interface AlphabakeVtonV1Response {
  kind: AlphabakeVtonV1ResponseKind;
  output: OperationOutputImageSingle;
  input: AlphabakeVtonV1ResponseInput;
  status: AlphabakeVtonV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: AlphabakeVtonV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
