/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AlphabakeVtonV1InputGarmentType = typeof AlphabakeVtonV1InputGarmentType[keyof typeof AlphabakeVtonV1InputGarmentType];


export const AlphabakeVtonV1InputGarmentType = {
  top: 'top',
  bottom: 'bottom',
  full: 'full',
} as const;
