/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AlphabakeVtonV1InputMode = typeof AlphabakeVtonV1InputMode[keyof typeof AlphabakeVtonV1InputMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlphabakeVtonV1InputMode = {
  fast: 'fast',
  quality: 'quality',
} as const;
