/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AnimateKling16ProV1ResponseKind = typeof AnimateKling16ProV1ResponseKind[keyof typeof AnimateKling16ProV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimateKling16ProV1ResponseKind = {
  operation: 'operation',
} as const;
