/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AnimateKling21V1InputDuration = typeof AnimateKling21V1InputDuration[keyof typeof AnimateKling21V1InputDuration];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimateKling21V1InputDuration = {
  NUMBER_5: '5',
  NUMBER_10: '10',
} as const;
