/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AnimateCreatomateV1ResponseStatus = typeof AnimateCreatomateV1ResponseStatus[keyof typeof AnimateCreatomateV1ResponseStatus];


export const AnimateCreatomateV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
