/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateKling16ProV1Input } from './animateKling16ProV1Input';
import type { AnimateKling16ProV1RequestMetadata } from './animateKling16ProV1RequestMetadata';

export interface AnimateKling16ProV1Request {
  input: AnimateKling16ProV1Input;
  metadata?: AnimateKling16ProV1RequestMetadata;
}
