/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AnimateKling16ProV1InputDuration = typeof AnimateKling16ProV1InputDuration[keyof typeof AnimateKling16ProV1InputDuration];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AnimateKling16ProV1InputDuration = {
  NUMBER_5: '5',
  NUMBER_10: '10',
} as const;
