/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateKling21V1Input } from './animateKling21V1Input';
import type { AnimateKling21V1RequestMetadata } from './animateKling21V1RequestMetadata';

export interface AnimateKling21V1Request {
  input: AnimateKling21V1Input;
  metadata?: AnimateKling21V1RequestMetadata;
}
