/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateKling21ProV1ResponseKind } from './animateKling21ProV1ResponseKind';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';
import type { AnimateKling21ProV1ResponseInput } from './animateKling21ProV1ResponseInput';
import type { AnimateKling21ProV1ResponseStatus } from './animateKling21ProV1ResponseStatus';
import type { AnimateKling21ProV1ResponseMetadata } from './animateKling21ProV1ResponseMetadata';

export interface AnimateKling21ProV1Response {
  kind: AnimateKling21ProV1ResponseKind;
  output: OperationOutputVideoSingle;
  input: AnimateKling21ProV1ResponseInput;
  status: AnimateKling21ProV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: AnimateKling21ProV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
