/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateKling21StandardV1ResponseKind } from './animateKling21StandardV1ResponseKind';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';
import type { AnimateKling21StandardV1ResponseInput } from './animateKling21StandardV1ResponseInput';
import type { AnimateKling21StandardV1ResponseStatus } from './animateKling21StandardV1ResponseStatus';
import type { AnimateKling21StandardV1ResponseMetadata } from './animateKling21StandardV1ResponseMetadata';

export interface AnimateKling21StandardV1Response {
  kind: AnimateKling21StandardV1ResponseKind;
  output: OperationOutputVideoSingle;
  input: AnimateKling21StandardV1ResponseInput;
  status: AnimateKling21StandardV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: AnimateKling21StandardV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
