/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateKling16ProV1ResponseKind } from './animateKling16ProV1ResponseKind';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';
import type { AnimateKling16ProV1ResponseInput } from './animateKling16ProV1ResponseInput';
import type { AnimateKling16ProV1ResponseStatus } from './animateKling16ProV1ResponseStatus';
import type { AnimateKling16ProV1ResponseMetadata } from './animateKling16ProV1ResponseMetadata';

export interface AnimateKling16ProV1Response {
  kind: AnimateKling16ProV1ResponseKind;
  output: OperationOutputVideoSingle;
  input: AnimateKling16ProV1ResponseInput;
  status: AnimateKling16ProV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  id: string;
  creatorId: string;
  metadata: AnimateKling16ProV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
