/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateCreatomateV1InputTemplate } from './animateCreatomateV1InputTemplate';

export interface AnimateCreatomateV1Input {
  template: AnimateCreatomateV1InputTemplate;
}
