/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateKling21V1InputDuration } from './animateKling21V1InputDuration';

export interface AnimateKling21V1Input {
  prompt: string;
  negativePrompt?: string;
  startImageId?: string;
  duration?: AnimateKling21V1InputDuration;
}
