/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AnimateKling21ProV1ResponseStatus = typeof AnimateKling21ProV1ResponseStatus[keyof typeof AnimateKling21ProV1ResponseStatus];


export const AnimateKling21ProV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
