/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateKling16ProV1InputAspectRatio } from './animateKling16ProV1InputAspectRatio';
import type { AnimateKling16ProV1InputDuration } from './animateKling16ProV1InputDuration';

export interface AnimateKling16ProV1Input {
  prompt: string;
  negativePrompt?: string;
  aspectRatio?: AnimateKling16ProV1InputAspectRatio;
  startImageId?: string;
  endImageId?: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  promptRelevance?: number;
  duration?: AnimateKling16ProV1InputDuration;
}
