/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type AnimateCreatomateV1ResponseKind = typeof AnimateCreatomateV1ResponseKind[keyof typeof AnimateCreatomateV1ResponseKind];


export const AnimateCreatomateV1ResponseKind = {
  operation: 'operation',
} as const;
