/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateCreatomateV1ResponseInput } from './animateCreatomateV1ResponseInput';
import type { AnimateCreatomateV1ResponseKind } from './animateCreatomateV1ResponseKind';
import type { AnimateCreatomateV1ResponseMetadata } from './animateCreatomateV1ResponseMetadata';
import type { AnimateCreatomateV1ResponseStatus } from './animateCreatomateV1ResponseStatus';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';

export interface AnimateCreatomateV1Response {
  kind: AnimateCreatomateV1ResponseKind;
  output: OperationOutputVideoSingle;
  input: AnimateCreatomateV1ResponseInput;
  status: AnimateCreatomateV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: AnimateCreatomateV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
