/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateKling21ProV1InputDuration } from './animateKling21ProV1InputDuration';

export interface AnimateKling21ProV1Input {
  prompt: string;
  negativePrompt?: string;
  startImageId: string;
  endImageId?: string;
  duration?: AnimateKling21ProV1InputDuration;
}
