/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateKling21V1ResponseKind } from './animateKling21V1ResponseKind';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';
import type { AnimateKling21V1ResponseInput } from './animateKling21V1ResponseInput';
import type { AnimateKling21V1ResponseStatus } from './animateKling21V1ResponseStatus';
import type { AnimateKling21V1ResponseMetadata } from './animateKling21V1ResponseMetadata';

export interface AnimateKling21V1Response {
  kind: AnimateKling21V1ResponseKind;
  output: OperationOutputVideoSingle;
  input: AnimateKling21V1ResponseInput;
  status: AnimateKling21V1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  id: string;
  creatorId: string;
  metadata: AnimateKling21V1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
