/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { AnimateCreatomateV1Input } from './animateCreatomateV1Input';
import type { AnimateCreatomateV1RequestMetadata } from './animateCreatomateV1RequestMetadata';

export interface AnimateCreatomateV1Request {
  input: AnimateCreatomateV1Input;
  metadata?: AnimateCreatomateV1RequestMetadata;
}
