/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface CaseDto {
  /** Case key to match against */
  key: string;
  /** Value to return when key matches */
  value: string;
}
