/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ChatControllerListChatsV1OrderBy = typeof ChatControllerListChatsV1OrderBy[keyof typeof ChatControllerListChatsV1OrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatControllerListChatsV1OrderBy = {
  createdAt_ASC: 'createdAt_ASC',
  createdAt_DESC: 'createdAt_DESC',
  updatedAt_ASC: 'updatedAt_ASC',
  updatedAt_DESC: 'updatedAt_DESC',
} as const;
