/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ChatControllerListChatsV1OrderBy } from './chatControllerListChatsV1OrderBy';

export type ChatControllerListChatsV1Params = {
orderBy?: ChatControllerListChatsV1OrderBy;
limit?: number;
cursor?: string;
};
