/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ClassifyImageOutputDto } from './classifyImageOutputDto';
import type { ClipClassifyV1ResponseInput } from './clipClassifyV1ResponseInput';
import type { ClipClassifyV1ResponseKind } from './clipClassifyV1ResponseKind';
import type { ClipClassifyV1ResponseMetadata } from './clipClassifyV1ResponseMetadata';
import type { ClipClassifyV1ResponseStatus } from './clipClassifyV1ResponseStatus';

export interface ClipClassifyV1Response {
  kind: ClipClassifyV1ResponseKind;
  output: ClassifyImageOutputDto;
  input: ClipClassifyV1ResponseInput;
  status: ClipClassifyV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: ClipClassifyV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
