/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ClassifyImageInputDto } from './classifyImageInputDto';
import type { ClipClassifyV1RequestMetadata } from './clipClassifyV1RequestMetadata';

export interface ClipClassifyV1Request {
  input: ClassifyImageInputDto;
  metadata?: ClipClassifyV1RequestMetadata;
}
