/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ClipClassifyV1ResponseStatus = typeof ClipClassifyV1ResponseStatus[keyof typeof ClipClassifyV1ResponseStatus];


export const ClipClassifyV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
