/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { CollectionsControllerListCollectionsV1OrderBy } from './collectionsControllerListCollectionsV1OrderBy';

export type CollectionsControllerListCollectionsV1Params = {
orderBy?: CollectionsControllerListCollectionsV1OrderBy;
limit?: number;
cursor?: string;
};
