/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { CollectionsControllerListItemsV1Kind } from './collectionsControllerListItemsV1Kind';
import type { CollectionsControllerListItemsV1OrderBy } from './collectionsControllerListItemsV1OrderBy';

export type CollectionsControllerListItemsV1Params = {
cursor?: string;
orderBy?: CollectionsControllerListItemsV1OrderBy;
limit?: number;
kind?: CollectionsControllerListItemsV1Kind;
};
