/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type CollectionsControllerListItemsV1Kind = typeof CollectionsControllerListItemsV1Kind[keyof typeof CollectionsControllerListItemsV1Kind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CollectionsControllerListItemsV1Kind = {
  collection: 'collection',
  operation: 'operation',
  stack: 'stack',
  image: 'image',
  video: 'video',
  pose: 'pose',
  storage: 'storage',
  pipeline: 'pipeline',
  workflow: 'workflow',
} as const;
