/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type CompositeV1ResponseStatus = typeof CompositeV1ResponseStatus[keyof typeof CompositeV1ResponseStatus];


export const CompositeV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
