/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type CompositeV1ResponseKind = typeof CompositeV1ResponseKind[keyof typeof CompositeV1ResponseKind];


export const CompositeV1ResponseKind = {
  operation: 'operation',
} as const;
