/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { CompositeElementBlend } from './compositeElementBlend';
import type { CompositeElementFit } from './compositeElementFit';

export interface CompositeElement {
  /** libvips blending mode */
  blend?: CompositeElementBlend;
  imageId: string;
  /**
   * @minimum 0
   * @maximum 8192
   */
  left: number;
  /**
   * @minimum 0
   * @maximum 8192
   */
  top: number;
  /**
   * @minimum 1
   * @maximum 8192
   */
  width: number;
  /**
   * @minimum 1
   * @maximum 8192
   */
  height: number;
  fit: CompositeElementFit;
}
