/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ContrastV1ResponseKind = typeof ContrastV1ResponseKind[keyof typeof ContrastV1ResponseKind];


export const ContrastV1ResponseKind = {
  operation: 'operation',
} as const;
