/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ContrastV1ResponseInput } from './contrastV1ResponseInput';
import type { ContrastV1ResponseKind } from './contrastV1ResponseKind';
import type { ContrastV1ResponseMetadata } from './contrastV1ResponseMetadata';
import type { ContrastV1ResponseStatus } from './contrastV1ResponseStatus';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';

export interface ContrastV1Response {
  kind: ContrastV1ResponseKind;
  output: OperationOutputImageSingle;
  input: ContrastV1ResponseInput;
  status: ContrastV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: ContrastV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
