/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { CreateWorkflowParamsDtoData } from './createWorkflowParamsDtoData';
import type { CreateWorkflowParamsDtoPipelineTemplate } from './createWorkflowParamsDtoPipelineTemplate';
import type { CreateWorkflowParamsDtoMetadata } from './createWorkflowParamsDtoMetadata';

export interface CreateWorkflowParamsDto {
  data: CreateWorkflowParamsDtoData;
  pipelineTemplate?: CreateWorkflowParamsDtoPipelineTemplate;
  version: string;
  metadata?: CreateWorkflowParamsDtoMetadata;
  customExecutionPrice?: string;
}
