/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface CreateImageParamsDto {
  fileToken?: string;
  /** @minimum 1 */
  ttlSeconds?: number;
}
