/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { CreatePipelineTaskDtoArgsItemOneOf } from './createPipelineTaskDtoArgsItemOneOf';

/**
 * @nullable
 */
export type CreatePipelineTaskDtoArgsItem = CreatePipelineTaskDtoArgsItemOneOf | boolean | number | string | null;
