/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface CropV1Input {
  imageId: string;
  left: number;
  top: number;
  width: number;
  height: number;
}
