/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type CutV1ResponseKind = typeof CutV1ResponseKind[keyof typeof CutV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CutV1ResponseKind = {
  operation: 'operation',
} as const;
