/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { CutV1Input } from './cutV1Input';
import type { CutV1RequestMetadata } from './cutV1RequestMetadata';

export interface CutV1Request {
  input: CutV1Input;
  metadata?: CutV1RequestMetadata;
}
