/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type EchoV1ResponseStatus = typeof EchoV1ResponseStatus[keyof typeof EchoV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EchoV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
