/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface EditFluxKontextDevV1Input {
  prompt: string;
  imageId?: string;
  /**
   * @minimum 4
   * @maximum 50
   */
  numberOfSteps?: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  guidance?: number;
  seed?: number;
}
