/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type EditFluxKontextDevV1ResponseKind = typeof EditFluxKontextDevV1ResponseKind[keyof typeof EditFluxKontextDevV1ResponseKind];


export const EditFluxKontextDevV1ResponseKind = {
  operation: 'operation',
} as const;
