/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { EditFlux2KleinV1ResponseKind } from './editFlux2KleinV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { EditFlux2KleinV1ResponseInput } from './editFlux2KleinV1ResponseInput';
import type { EditFlux2KleinV1ResponseStatus } from './editFlux2KleinV1ResponseStatus';
import type { EditFlux2KleinV1ResponseMetadata } from './editFlux2KleinV1ResponseMetadata';

export interface EditFlux2KleinV1Response {
  kind: EditFlux2KleinV1ResponseKind;
  output: OperationOutputImageSingle;
  input: EditFlux2KleinV1ResponseInput;
  status: EditFlux2KleinV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: EditFlux2KleinV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
