/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { EditFluxKontextDevV1Input } from './editFluxKontextDevV1Input';
import type { EditFluxKontextDevV1RequestMetadata } from './editFluxKontextDevV1RequestMetadata';

export interface EditFluxKontextDevV1Request {
  input: EditFluxKontextDevV1Input;
  metadata?: EditFluxKontextDevV1RequestMetadata;
}
