/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type FashnVtonV1InputGarmentPhotoType = typeof FashnVtonV1InputGarmentPhotoType[keyof typeof FashnVtonV1InputGarmentPhotoType];


export const FashnVtonV1InputGarmentPhotoType = {
  auto: 'auto',
  model: 'model',
  'flat-lay': 'flat-lay',
} as const;
