/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type FashnVtonV1InputMode = typeof FashnVtonV1InputMode[keyof typeof FashnVtonV1InputMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FashnVtonV1InputMode = {
  performance: 'performance',
  balanced: 'balanced',
  quality: 'quality',
} as const;
