/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { FashnVton16V1RequestMetadata } from './fashnVton16V1RequestMetadata';
import type { FashnVtonV1Input } from './fashnVtonV1Input';

export interface FashnVton16V1Request {
  input: FashnVtonV1Input;
  metadata?: FashnVton16V1RequestMetadata;
}
