/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type FashnVton16V1ResponseStatus = typeof FashnVton16V1ResponseStatus[keyof typeof FashnVton16V1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FashnVton16V1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
