/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { FluxKontextTrainOutputDtoKind } from './fluxKontextTrainOutputDtoKind';
import type { FluxKontextTrainResultDto } from './fluxKontextTrainResultDto';

export interface FluxKontextTrainOutputDto {
  kind: FluxKontextTrainOutputDtoKind;
  data: FluxKontextTrainResultDto;
}
