/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type FluxKontextDevV1ResponseKind = typeof FluxKontextDevV1ResponseKind[keyof typeof FluxKontextDevV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FluxKontextDevV1ResponseKind = {
  operation: 'operation',
} as const;
