/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { FluxKontextDevTrainV1ResponseKind } from './fluxKontextDevTrainV1ResponseKind';
import type { FluxKontextTrainOutputDto } from './fluxKontextTrainOutputDto';
import type { FluxKontextDevTrainV1ResponseInput } from './fluxKontextDevTrainV1ResponseInput';
import type { FluxKontextDevTrainV1ResponseStatus } from './fluxKontextDevTrainV1ResponseStatus';
import type { FluxKontextDevTrainV1ResponseMetadata } from './fluxKontextDevTrainV1ResponseMetadata';

export interface FluxKontextDevTrainV1Response {
  kind: FluxKontextDevTrainV1ResponseKind;
  output: FluxKontextTrainOutputDto;
  input: FluxKontextDevTrainV1ResponseInput;
  status: FluxKontextDevTrainV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: FluxKontextDevTrainV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
