/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { FluxKontextDevV1ResponseInput } from './fluxKontextDevV1ResponseInput';
import type { FluxKontextDevV1ResponseKind } from './fluxKontextDevV1ResponseKind';
import type { FluxKontextDevV1ResponseMetadata } from './fluxKontextDevV1ResponseMetadata';
import type { FluxKontextDevV1ResponseStatus } from './fluxKontextDevV1ResponseStatus';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';

export interface FluxKontextDevV1Response {
  kind: FluxKontextDevV1ResponseKind;
  output: OperationOutputImageSingle;
  input: FluxKontextDevV1ResponseInput;
  status: FluxKontextDevV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: FluxKontextDevV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
