/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type FluxKontextV1ResponseKind = typeof FluxKontextV1ResponseKind[keyof typeof FluxKontextV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FluxKontextV1ResponseKind = {
  operation: 'operation',
} as const;
