/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Flux11ProUltraV1Input } from './flux11ProUltraV1Input';
import type { Flux11ProUltraV1RequestMetadata } from './flux11ProUltraV1RequestMetadata';

export interface Flux11ProUltraV1Request {
  input: Flux11ProUltraV1Input;
  metadata?: Flux11ProUltraV1RequestMetadata;
}
