/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { FluxKontextPrepareDatasetV1ResponseKind } from './fluxKontextPrepareDatasetV1ResponseKind';
import type { FluxKontextPrepareDatasetOutputDto } from './fluxKontextPrepareDatasetOutputDto';
import type { FluxKontextPrepareDatasetV1ResponseInput } from './fluxKontextPrepareDatasetV1ResponseInput';
import type { FluxKontextPrepareDatasetV1ResponseStatus } from './fluxKontextPrepareDatasetV1ResponseStatus';
import type { FluxKontextPrepareDatasetV1ResponseMetadata } from './fluxKontextPrepareDatasetV1ResponseMetadata';

export interface FluxKontextPrepareDatasetV1Response {
  kind: FluxKontextPrepareDatasetV1ResponseKind;
  output: FluxKontextPrepareDatasetOutputDto;
  input: FluxKontextPrepareDatasetV1ResponseInput;
  status: FluxKontextPrepareDatasetV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: FluxKontextPrepareDatasetV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
