/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { FluxKontextPrepareDatasetInputDto } from './fluxKontextPrepareDatasetInputDto';
import type { FluxKontextDevPrepareDatasetV1RequestMetadata } from './fluxKontextDevPrepareDatasetV1RequestMetadata';

export interface FluxKontextDevPrepareDatasetV1Request {
  input: FluxKontextPrepareDatasetInputDto;
  metadata?: FluxKontextDevPrepareDatasetV1RequestMetadata;
}
