/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type FluxKontextPrepareDatasetV1ResponseKind = typeof FluxKontextPrepareDatasetV1ResponseKind[keyof typeof FluxKontextPrepareDatasetV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FluxKontextPrepareDatasetV1ResponseKind = {
  operation: 'operation',
} as const;
