/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type FluxKontextDevV1ResponseStatus = typeof FluxKontextDevV1ResponseStatus[keyof typeof FluxKontextDevV1ResponseStatus];


export const FluxKontextDevV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
