/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type FluxKontextDevPrepareDatasetV1ResponseKind = typeof FluxKontextDevPrepareDatasetV1ResponseKind[keyof typeof FluxKontextDevPrepareDatasetV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FluxKontextDevPrepareDatasetV1ResponseKind = {
  operation: 'operation',
} as const;
