/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type FluxKontextTrainOutputDtoKind = typeof FluxKontextTrainOutputDtoKind[keyof typeof FluxKontextTrainOutputDtoKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FluxKontextTrainOutputDtoKind = {
  json: 'json',
} as const;
