/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type FluxKontextDevTrainV1ResponseStatus = typeof FluxKontextDevTrainV1ResponseStatus[keyof typeof FluxKontextDevTrainV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FluxKontextDevTrainV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
