/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Flux11ProUltraV1ResponseKind } from './flux11ProUltraV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { Flux11ProUltraV1ResponseInput } from './flux11ProUltraV1ResponseInput';
import type { Flux11ProUltraV1ResponseStatus } from './flux11ProUltraV1ResponseStatus';
import type { Flux11ProUltraV1ResponseMetadata } from './flux11ProUltraV1ResponseMetadata';

export interface Flux11ProUltraV1Response {
  kind: Flux11ProUltraV1ResponseKind;
  output: OperationOutputImageSingle;
  input: Flux11ProUltraV1ResponseInput;
  status: Flux11ProUltraV1ResponseStatus;
  type: string;
  price?: string;
  id: string;
  creatorId: string;
  metadata: Flux11ProUltraV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
