/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Output image format
 */
export type GoogleNanoBananaV1InputOutputFormat = typeof GoogleNanoBananaV1InputOutputFormat[keyof typeof GoogleNanoBananaV1InputOutputFormat];


export const GoogleNanoBananaV1InputOutputFormat = {
  jpg: 'jpg',
  png: 'png',
} as const;
