/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Output resolution preset
 */
export type GoogleNanoBananaProEditV1InputResolution = typeof GoogleNanoBananaProEditV1InputResolution[keyof typeof GoogleNanoBananaProEditV1InputResolution];


export const GoogleNanoBananaProEditV1InputResolution = {
  '1K': '1K',
  '2K': '2K',
  '4K': '4K',
} as const;
