/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GoogleNanoBananaV1InputOutputFormat } from './googleNanoBananaV1InputOutputFormat';
import type { GoogleNanoBananaV1InputAspectRatio } from './googleNanoBananaV1InputAspectRatio';

export interface GoogleNanoBananaV1Input {
  /** IDs of input images to guide generation */
  imageIds?: string[];
  /** Text prompt for generation */
  prompt: string;
  /** Output image format */
  outputFormat?: GoogleNanoBananaV1InputOutputFormat;
  /** Aspect ratio of the generated image */
  aspectRatio?: GoogleNanoBananaV1InputAspectRatio;
}
