/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Desired aspect ratio
 */
export type GoogleNanoBanana2V1InputAspectRatio = typeof GoogleNanoBanana2V1InputAspectRatio[keyof typeof GoogleNanoBanana2V1InputAspectRatio];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoogleNanoBanana2V1InputAspectRatio = {
  match_input_image: 'match_input_image',
  '1:1': '1:1',
  '1:4': '1:4',
  '1:8': '1:8',
  '2:3': '2:3',
  '3:2': '3:2',
  '3:4': '3:4',
  '4:1': '4:1',
  '4:3': '4:3',
  '4:5': '4:5',
  '5:4': '5:4',
  '8:1': '8:1',
  '9:16': '9:16',
  '16:9': '16:9',
  '21:9': '21:9',
} as const;
