/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GoogleNanoBananaV1ResponseKind = typeof GoogleNanoBananaV1ResponseKind[keyof typeof GoogleNanoBananaV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoogleNanoBananaV1ResponseKind = {
  operation: 'operation',
} as const;
