/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GoogleNanoBanana2V1Input } from './googleNanoBanana2V1Input';
import type { GoogleNanoBanana2V1RequestMetadata } from './googleNanoBanana2V1RequestMetadata';

export interface GoogleNanoBanana2V1Request {
  input: GoogleNanoBanana2V1Input;
  metadata?: GoogleNanoBanana2V1RequestMetadata;
}
