/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GoogleNanoBananaProEditV1ResponseStatus = typeof GoogleNanoBananaProEditV1ResponseStatus[keyof typeof GoogleNanoBananaProEditV1ResponseStatus];


export const GoogleNanoBananaProEditV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
