/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Output resolution preset
 */
export type GoogleNanoBananaProEditV1InputResolution = typeof GoogleNanoBananaProEditV1InputResolution[keyof typeof GoogleNanoBananaProEditV1InputResolution];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoogleNanoBananaProEditV1InputResolution = {
  '1K': '1K',
  '2K': '2K',
  '4K': '4K',
} as const;
