/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GoogleNanoBananaV1ResponseKind = typeof GoogleNanoBananaV1ResponseKind[keyof typeof GoogleNanoBananaV1ResponseKind];


export const GoogleNanoBananaV1ResponseKind = {
  operation: 'operation',
} as const;
