/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Aspect ratio of the generated image
 */
export type GoogleNanoBananaV1InputAspectRatio = typeof GoogleNanoBananaV1InputAspectRatio[keyof typeof GoogleNanoBananaV1InputAspectRatio];


export const GoogleNanoBananaV1InputAspectRatio = {
  '1:1': '1:1',
  '16:9': '16:9',
  '9:16': '9:16',
  '3:4': '3:4',
  '4:3': '4:3',
} as const;
