/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GoogleNanoBananaProEditV1InputAspectRatio } from './googleNanoBananaProEditV1InputAspectRatio';
import type { GoogleNanoBananaProEditV1InputResolution } from './googleNanoBananaProEditV1InputResolution';

export interface GoogleNanoBananaProEditV1Input {
  /** Text prompt describing the desired edit */
  prompt: string;
  /**
   * IDs of existing images to edit
   * @minItems 1
   */
  imageIds: string[];
  /** Output aspect ratio */
  aspectRatio?: GoogleNanoBananaProEditV1InputAspectRatio;
  /** Output resolution preset */
  resolution?: GoogleNanoBananaProEditV1InputResolution;
}
