/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Target resolution preset
 */
export type GoogleNanoBanana2V1InputResolution = typeof GoogleNanoBanana2V1InputResolution[keyof typeof GoogleNanoBanana2V1InputResolution];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoogleNanoBanana2V1InputResolution = {
  '1K': '1K',
  '2K': '2K',
  '4K': '4K',
} as const;
