/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GoogleNanoBananaV1InputOutputFormat = typeof GoogleNanoBananaV1InputOutputFormat[keyof typeof GoogleNanoBananaV1InputOutputFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoogleNanoBananaV1InputOutputFormat = {
  jpg: 'jpg',
  png: 'png',
} as const;
