/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Output image format
 */
export type GoogleNanoBanana2V1InputOutputFormat = typeof GoogleNanoBanana2V1InputOutputFormat[keyof typeof GoogleNanoBanana2V1InputOutputFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoogleNanoBanana2V1InputOutputFormat = {
  jpg: 'jpg',
  png: 'png',
} as const;
