/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GoogleNanoBananaV1ResponseStatus = typeof GoogleNanoBananaV1ResponseStatus[keyof typeof GoogleNanoBananaV1ResponseStatus];


export const GoogleNanoBananaV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
