/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GoogleNanoBananaV1ResponseInput } from './googleNanoBananaV1ResponseInput';
import type { GoogleNanoBananaV1ResponseKind } from './googleNanoBananaV1ResponseKind';
import type { GoogleNanoBananaV1ResponseMetadata } from './googleNanoBananaV1ResponseMetadata';
import type { GoogleNanoBananaV1ResponseStatus } from './googleNanoBananaV1ResponseStatus';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';

export interface GoogleNanoBananaV1Response {
  kind: GoogleNanoBananaV1ResponseKind;
  output: OperationOutputImageSingle;
  input: GoogleNanoBananaV1ResponseInput;
  status: GoogleNanoBananaV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: GoogleNanoBananaV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
