/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Target resolution preset
 */
export type GoogleNanoBanana2V1InputResolution = typeof GoogleNanoBanana2V1InputResolution[keyof typeof GoogleNanoBanana2V1InputResolution];


export const GoogleNanoBanana2V1InputResolution = {
  '1K': '1K',
  '2K': '2K',
  '4K': '4K',
} as const;
