/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GoogleNanoBananaV1Input } from './googleNanoBananaV1Input';
import type { GoogleNanoBananaV1RequestMetadata } from './googleNanoBananaV1RequestMetadata';

export interface GoogleNanoBananaV1Request {
  input: GoogleNanoBananaV1Input;
  metadata?: GoogleNanoBananaV1RequestMetadata;
}
