/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseLocalShellCallActionDtoType = typeof GPTV3ResponseLocalShellCallActionDtoType[keyof typeof GPTV3ResponseLocalShellCallActionDtoType];


export const GPTV3ResponseLocalShellCallActionDtoType = {
  exec: 'exec',
} as const;
