/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseInputItemImageGenerationCallDtoStatus = typeof GPTV3ResponseInputItemImageGenerationCallDtoStatus[keyof typeof GPTV3ResponseInputItemImageGenerationCallDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseInputItemImageGenerationCallDtoStatus = {
  in_progress: 'in_progress',
  completed: 'completed',
  generating: 'generating',
  failed: 'failed',
} as const;
