/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3FileSearchCallDtoType } from './gPTV3FileSearchCallDtoType';
import type { GPTV3FileSearchCallDetailsDto } from './gPTV3FileSearchCallDetailsDto';

export interface GPTV3FileSearchCallDto {
  /** The unique identifier for this tool call. */
  id: string;
  /** The type of tool call: file_search. */
  type: GPTV3FileSearchCallDtoType;
  /** The file search call details. */
  file_search: GPTV3FileSearchCallDetailsDto;
}
