/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseCodeInterpreterToolCallLogsDto } from './gPTV3ResponseCodeInterpreterToolCallLogsDto';
import type { GPTV3ResponseCodeInterpreterToolCallImageDto } from './gPTV3ResponseCodeInterpreterToolCallImageDto';

export type GPTV3ResponseCodeInterpreterToolCallDtoOutputsItem = GPTV3ResponseCodeInterpreterToolCallLogsDto | GPTV3ResponseCodeInterpreterToolCallImageDto;
