/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of the tool call.
 */
export type GPTV3ResponseFunctionToolCallDtoType = typeof GPTV3ResponseFunctionToolCallDtoType[keyof typeof GPTV3ResponseFunctionToolCallDtoType];


export const GPTV3ResponseFunctionToolCallDtoType = {
  function_call: 'function_call',
} as const;
