/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of the message. This is the SECOND output item when file_search or web_search tool is called, containing the model response with citations.
 */
export type GPTV3ResponseOutputMessageDtoType = typeof GPTV3ResponseOutputMessageDtoType[keyof typeof GPTV3ResponseOutputMessageDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseOutputMessageDtoType = {
  message: 'message',
} as const;
