/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseComputerToolCallScrollDtoType } from './gPTV3ResponseComputerToolCallScrollDtoType';

export interface GPTV3ResponseComputerToolCallScrollDto {
  type: GPTV3ResponseComputerToolCallScrollDtoType;
  scroll_x: number;
  scroll_y: number;
  x: number;
  y: number;
}
