/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseOutputItemImageGenerationCallDto } from './gPTV3ResponseOutputItemImageGenerationCallDto';

export interface GPTV3ResponseImageGenerationResultsDto {
  /** Array of image generation results. */
  results: GPTV3ResponseOutputItemImageGenerationCallDto[];
}
