/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3WebSearchToolDtoSearchContextSize } from './gPTV3WebSearchToolDtoSearchContextSize';
import type { GPTV3WebSearchToolDtoType } from './gPTV3WebSearchToolDtoType';

export interface GPTV3WebSearchToolDto {
  /** The type of the tool. */
  type: GPTV3WebSearchToolDtoType;
  /** High level guidance for the amount of context window space to use for the search. */
  search_context_size?: GPTV3WebSearchToolDtoSearchContextSize;
}
