/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseInputFunctionCallOutputDtoType = typeof GPTV3ResponseInputFunctionCallOutputDtoType[keyof typeof GPTV3ResponseInputFunctionCallOutputDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseInputFunctionCallOutputDtoType = {
  function_call_output: 'function_call_output',
} as const;
