/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseComputerToolCallScreenshotDtoType = typeof GPTV3ResponseComputerToolCallScreenshotDtoType[keyof typeof GPTV3ResponseComputerToolCallScreenshotDtoType];


export const GPTV3ResponseComputerToolCallScreenshotDtoType = {
  screenshot: 'screenshot',
} as const;
