/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of tool call: file_search.
 */
export type GPTV3FileSearchCallDtoType = typeof GPTV3FileSearchCallDtoType[keyof typeof GPTV3FileSearchCallDtoType];


export const GPTV3FileSearchCallDtoType = {
  file_search: 'file_search',
} as const;
