/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Controls how the model chooses tools: "none" disables, "auto" lets the model decide, "required" forces a tool call, or specify an explicit tool choice.
 */
export type GPTV3InputToolChoice = { [key: string]: unknown };
