/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseFormatTextDtoType } from './gPTV3ResponseFormatTextDtoType';

export interface GPTV3ResponseFormatTextDto {
  /** The type of response format being defined: 'text'. */
  type: GPTV3ResponseFormatTextDtoType;
}
