/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type GPTV3ResponseInputItemReferenceDtoType = typeof GPTV3ResponseInputItemReferenceDtoType[keyof typeof GPTV3ResponseInputItemReferenceDtoType] | null;


export const GPTV3ResponseInputItemReferenceDtoType = {
  item_reference: 'item_reference',
} as const;
