/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3DeveloperMessageDtoContentOneOfItem } from './gPTV3DeveloperMessageDtoContentOneOfItem';

/**
 * The content of the developer message. Can be a string or an array of text and image inputs.
 */
export type GPTV3DeveloperMessageDtoContent = string | GPTV3DeveloperMessageDtoContentOneOfItem[];
