/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseCodeInterpreterToolCallLogsDtoType } from './gPTV3ResponseCodeInterpreterToolCallLogsDtoType';

export interface GPTV3ResponseCodeInterpreterToolCallLogsDto {
  type: GPTV3ResponseCodeInterpreterToolCallLogsDtoType;
  logs: string;
}
