/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The role of the message sender.
 */
export type GPTV2ToolMessageDtoRole = typeof GPTV2ToolMessageDtoRole[keyof typeof GPTV2ToolMessageDtoRole];


export const GPTV2ToolMessageDtoRole = {
  tool: 'tool',
} as const;
