/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseInputItemImageGenerationCallDtoType = typeof GPTV3ResponseInputItemImageGenerationCallDtoType[keyof typeof GPTV3ResponseInputItemImageGenerationCallDtoType];


export const GPTV3ResponseInputItemImageGenerationCallDtoType = {
  image_generation_call: 'image_generation_call',
} as const;
