/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3TextInputDto } from './gPTV3TextInputDto';
import type { GPTV3ImageInputDto } from './gPTV3ImageInputDto';

export type GPTV3UserMessageDtoContentOneOfItem = GPTV3TextInputDto | GPTV3ImageInputDto;
