/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseInputMcpListToolsToolDto } from './gPTV3ResponseInputMcpListToolsToolDto';
import type { GPTV3ResponseInputMcpListToolsDtoType } from './gPTV3ResponseInputMcpListToolsDtoType';

export interface GPTV3ResponseInputMcpListToolsDto {
  id: string;
  server_label: string;
  tools: GPTV3ResponseInputMcpListToolsToolDto[];
  type: GPTV3ResponseInputMcpListToolsDtoType;
  /** @nullable */
  error?: string | null;
}
