/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseComputerToolCallClickDtoButton = typeof GPTV3ResponseComputerToolCallClickDtoButton[keyof typeof GPTV3ResponseComputerToolCallClickDtoButton];


export const GPTV3ResponseComputerToolCallClickDtoButton = {
  left: 'left',
  right: 'right',
  wheel: 'wheel',
  back: 'back',
  forward: 'forward',
} as const;
