/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseInputLocalShellCallActionDtoType = typeof GPTV3ResponseInputLocalShellCallActionDtoType[keyof typeof GPTV3ResponseInputLocalShellCallActionDtoType];


export const GPTV3ResponseInputLocalShellCallActionDtoType = {
  exec: 'exec',
} as const;
