/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV2Input } from './gPTV2Input';
import type { GptV2RequestMetadata } from './gptV2RequestMetadata';

export interface GptV2Request {
  input: GPTV2Input;
  metadata?: GptV2RequestMetadata;
}
