/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of tool call: image_generation.
 */
export type GPTV3ImageGenerationCallDtoType = typeof GPTV3ImageGenerationCallDtoType[keyof typeof GPTV3ImageGenerationCallDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ImageGenerationCallDtoType = {
  image_generation: 'image_generation',
} as const;
