/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GptV1ResponseStatus = typeof GptV1ResponseStatus[keyof typeof GptV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GptV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
