/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The finish reason for the response.
 */
export type GPTV3ResponseDtoFinishReason = typeof GPTV3ResponseDtoFinishReason[keyof typeof GPTV3ResponseDtoFinishReason];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseDtoFinishReason = {
  stop: 'stop',
  tool_calls: 'tool_calls',
} as const;
