/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseOutputItemImageGenerationCallDtoMetadata } from './gPTV3ResponseOutputItemImageGenerationCallDtoMetadata';
import type { GPTV3ResponseOutputItemImageGenerationCallDtoStatus } from './gPTV3ResponseOutputItemImageGenerationCallDtoStatus';
import type { GPTV3ResponseOutputItemImageGenerationCallDtoType } from './gPTV3ResponseOutputItemImageGenerationCallDtoType';

export interface GPTV3ResponseOutputItemImageGenerationCallDto {
  /** The type of the image generation output item. */
  type: GPTV3ResponseOutputItemImageGenerationCallDtoType;
  /** The unique identifier for this image generation call. */
  id: string;
  /** The status of the image generation call. */
  status: GPTV3ResponseOutputItemImageGenerationCallDtoStatus;
  /** The generated image ID (when conversion is successful). */
  imageId?: string;
  /** The format of the generated image (e.g., "png", "jpeg"). */
  format?: string;
  /** The size of the generated image in bytes. */
  size?: number;
  /** Error message if the image generation failed. */
  error?: string;
  /** Additional metadata about the image generation. */
  metadata?: GPTV3ResponseOutputItemImageGenerationCallDtoMetadata;
}
