/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseComputerToolCallDtoAction } from './gPTV3ResponseComputerToolCallDtoAction';
import type { GPTV3ResponseComputerToolCallPendingSafetyCheckDto } from './gPTV3ResponseComputerToolCallPendingSafetyCheckDto';
import type { GPTV3ResponseComputerToolCallDtoStatus } from './gPTV3ResponseComputerToolCallDtoStatus';
import type { GPTV3ResponseComputerToolCallDtoType } from './gPTV3ResponseComputerToolCallDtoType';

export interface GPTV3ResponseComputerToolCallDto {
  /** The unique ID of the computer call. */
  id: string;
  /** The action requested for the computer call. */
  action: GPTV3ResponseComputerToolCallDtoAction;
  /** The ID of the tool call. */
  call_id: string;
  /** Pending safety checks for the computer call. */
  pending_safety_checks: GPTV3ResponseComputerToolCallPendingSafetyCheckDto[];
  status: GPTV3ResponseComputerToolCallDtoStatus;
  type: GPTV3ResponseComputerToolCallDtoType;
}
