/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseOutputTextFileCitationDtoType } from './gPTV3ResponseOutputTextFileCitationDtoType';

export interface GPTV3ResponseOutputTextFileCitationDto {
  /** The ID of the file. */
  file_id: string;
  /** The filename of the file cited. */
  filename: string;
  /** The index of the file in the list of files. */
  index: number;
  type: GPTV3ResponseOutputTextFileCitationDtoType;
}
