/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Controls which (if any) tool is called by the model. 'none', 'auto', 'required', or a specific function tool.
 */
export type GPTV2ToolChoiceDtoType = typeof GPTV2ToolChoiceDtoType[keyof typeof GPTV2ToolChoiceDtoType];


export const GPTV2ToolChoiceDtoType = {
  none: 'none',
  auto: 'auto',
  required: 'required',
  function: 'function',
} as const;
