/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseInputLocalShellCallOutputDtoStatus = typeof GPTV3ResponseInputLocalShellCallOutputDtoStatus[keyof typeof GPTV3ResponseInputLocalShellCallOutputDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseInputLocalShellCallOutputDtoStatus = {
  in_progress: 'in_progress',
  completed: 'completed',
  incomplete: 'incomplete',
} as const;
