/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The parameters the functions accepts, described satisfies a JSON Schema object.
 */
export type GPTV3FunctionToolDtoParameters = { [key: string]: unknown };
