/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV2ToolChoiceDtoType } from './gPTV2ToolChoiceDtoType';
import type { GPTV2ToolChoiceFunctionDto } from './gPTV2ToolChoiceFunctionDto';

export interface GPTV2ToolChoiceDto {
  /** Controls which (if any) tool is called by the model. 'none', 'auto', 'required', or a specific function tool. */
  type: GPTV2ToolChoiceDtoType;
  /** The function to call, if type is `function`. */
  function?: GPTV2ToolChoiceFunctionDto;
}
