/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The status of the file search call.
 */
export type GPTV3FileSearchResultDtoStatus = typeof GPTV3FileSearchResultDtoStatus[keyof typeof GPTV3FileSearchResultDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3FileSearchResultDtoStatus = {
  completed: 'completed',
  failed: 'failed',
  pending: 'pending',
} as const;
