/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseMcpListToolsToolDto } from './gPTV3ResponseMcpListToolsToolDto';
import type { GPTV3ResponseMcpListToolsDtoType } from './gPTV3ResponseMcpListToolsDtoType';

export interface GPTV3ResponseMcpListToolsDto {
  id: string;
  server_label: string;
  tools: GPTV3ResponseMcpListToolsToolDto[];
  type: GPTV3ResponseMcpListToolsDtoType;
  /** @nullable */
  error?: string | null;
}
