/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The schema for the response format, described as a JSON Schema object.
 */
export type GPTV2ResponseFormatJsonSchemaDetailsDtoSchema = { [key: string]: unknown };
