/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3Input } from './gPTV3Input';
import type { GptV3RequestMetadata } from './gptV3RequestMetadata';

export interface GptV3Request {
  input: GPTV3Input;
  metadata?: GptV3RequestMetadata;
}
