/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseInputComputerCallOutputScreenshotDtoType = typeof GPTV3ResponseInputComputerCallOutputScreenshotDtoType[keyof typeof GPTV3ResponseInputComputerCallOutputScreenshotDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseInputComputerCallOutputScreenshotDtoType = {
  computer_screenshot: 'computer_screenshot',
} as const;
