/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3DeveloperMessageDtoContent } from './gPTV3DeveloperMessageDtoContent';
import type { GPTV3DeveloperMessageDtoRole } from './gPTV3DeveloperMessageDtoRole';
import type { GPTV3DeveloperMessageDtoType } from './gPTV3DeveloperMessageDtoType';

export interface GPTV3DeveloperMessageDto {
  /** The content of the developer message. Can be a string or an array of text and image inputs. */
  content: GPTV3DeveloperMessageDtoContent;
  /** The role of the message sender. */
  role: GPTV3DeveloperMessageDtoRole;
  /** The type of the message input. Always message. */
  type: GPTV3DeveloperMessageDtoType;
}
