/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV2UserMessageDtoRole } from './gPTV2UserMessageDtoRole';

export interface GPTV2UserMessageDto {
  /** The content of the user message. */
  content: string;
  /** The role of the message sender. */
  role: GPTV2UserMessageDtoRole;
  /** The name of the sender, if applicable. */
  name?: string;
}
