/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GptV3ResponseStatus = typeof GptV3ResponseStatus[keyof typeof GptV3ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GptV3ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
