/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseFileSearchToolCallResultDtoAttributes } from './gPTV3ResponseFileSearchToolCallResultDtoAttributes';

export interface GPTV3ResponseFileSearchToolCallResultDto {
  /** Optional attributes map. */
  attributes: GPTV3ResponseFileSearchToolCallResultDtoAttributes;
  /** The unique ID of the file. */
  file_id?: string;
  /** The name of the file. */
  filename?: string;
  /** The relevance score of the file. */
  score?: number;
  /** The text that was retrieved from the file. */
  text?: string;
}
