/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseMcpCallDtoType } from './gPTV3ResponseMcpCallDtoType';

export interface GPTV3ResponseMcpCallDto {
  id: string;
  arguments: string;
  name: string;
  server_label: string;
  type: GPTV3ResponseMcpCallDtoType;
  /** @nullable */
  error?: string | null;
  /** @nullable */
  output?: string | null;
}
