/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The role of the message sender.
 */
export type GPTV2AssistantMessageDtoRole = typeof GPTV2AssistantMessageDtoRole[keyof typeof GPTV2AssistantMessageDtoRole];


export const GPTV2AssistantMessageDtoRole = {
  assistant: 'assistant',
} as const;
