/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of tool call: function.
 */
export type GPTV3FunctionCallDtoType = typeof GPTV3FunctionCallDtoType[keyof typeof GPTV3FunctionCallDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3FunctionCallDtoType = {
  function: 'function',
} as const;
