/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of tool call: web_search_preview.
 */
export type GPTV3WebSearchCallDtoType = typeof GPTV3WebSearchCallDtoType[keyof typeof GPTV3WebSearchCallDtoType];


export const GPTV3WebSearchCallDtoType = {
  web_search_preview: 'web_search_preview',
} as const;
