/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GptV3ResponseKind = typeof GptV3ResponseKind[keyof typeof GptV3ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GptV3ResponseKind = {
  operation: 'operation',
} as const;
