/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3InputInputOneOfItem } from './gPTV3InputInputOneOfItem';

/**
 * Text, image, or file inputs to the model, used to generate a response. Can be a simple string, a single message object, or an array of messages with different roles.
 */
export type GPTV3InputInput = string | GPTV3InputInputOneOfItem[];
