/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV2ToolFunctionDto } from './gPTV2ToolFunctionDto';
import type { GPTV2ToolDtoType } from './gPTV2ToolDtoType';

export interface GPTV2ToolDto {
  /** The function definition for the tool. Currently, only functions are supported. */
  function: GPTV2ToolFunctionDto;
  /** The type of the tool. Currently, only 'function' is supported. */
  type: GPTV2ToolDtoType;
}
