/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseComputerToolCallKeypressDtoType = typeof GPTV3ResponseComputerToolCallKeypressDtoType[keyof typeof GPTV3ResponseComputerToolCallKeypressDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseComputerToolCallKeypressDtoType = {
  keypress: 'keypress',
} as const;
