/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseReasoningItemSummaryDtoType = typeof GPTV3ResponseReasoningItemSummaryDtoType[keyof typeof GPTV3ResponseReasoningItemSummaryDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseReasoningItemSummaryDtoType = {
  summary_text: 'summary_text',
} as const;
