/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseInputItemMessageContentItem } from './gPTV3ResponseInputItemMessageContentItem';
import type { GPTV3ResponseInputItemMessageRole } from './gPTV3ResponseInputItemMessageRole';
import type { GPTV3ResponseInputItemMessageType } from './gPTV3ResponseInputItemMessageType';
import type { GPTV3ResponseInputItemMessageStatus } from './gPTV3ResponseInputItemMessageStatus';

export interface GPTV3ResponseInputItemMessage {
  /** A list of input items (text, image, file). */
  content: GPTV3ResponseInputItemMessageContentItem[];
  /** The role of the message sender. */
  role: GPTV3ResponseInputItemMessageRole;
  /** The type of the message input. Always message. */
  type?: GPTV3ResponseInputItemMessageType;
  status?: GPTV3ResponseInputItemMessageStatus;
}
