/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of the tool.
 */
export type GPTV3ImageGenerationToolDtoType = typeof GPTV3ImageGenerationToolDtoType[keyof typeof GPTV3ImageGenerationToolDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ImageGenerationToolDtoType = {
  image_generation: 'image_generation',
} as const;
