/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseComputerToolCallClickDto } from './gPTV3ResponseComputerToolCallClickDto';
import type { GPTV3ResponseComputerToolCallDoubleClickDto } from './gPTV3ResponseComputerToolCallDoubleClickDto';
import type { GPTV3ResponseComputerToolCallDragDto } from './gPTV3ResponseComputerToolCallDragDto';
import type { GPTV3ResponseComputerToolCallDtoStatus } from './gPTV3ResponseComputerToolCallDtoStatus';
import type { GPTV3ResponseComputerToolCallDtoType } from './gPTV3ResponseComputerToolCallDtoType';
import type { GPTV3ResponseComputerToolCallKeypressDto } from './gPTV3ResponseComputerToolCallKeypressDto';
import type { GPTV3ResponseComputerToolCallMoveDto } from './gPTV3ResponseComputerToolCallMoveDto';
import type { GPTV3ResponseComputerToolCallPendingSafetyCheckDto } from './gPTV3ResponseComputerToolCallPendingSafetyCheckDto';
import type { GPTV3ResponseComputerToolCallScreenshotDto } from './gPTV3ResponseComputerToolCallScreenshotDto';
import type { GPTV3ResponseComputerToolCallScrollDto } from './gPTV3ResponseComputerToolCallScrollDto';
import type { GPTV3ResponseComputerToolCallTypeDto } from './gPTV3ResponseComputerToolCallTypeDto';
import type { GPTV3ResponseComputerToolCallWaitDto } from './gPTV3ResponseComputerToolCallWaitDto';

export interface GPTV3ResponseComputerToolCallDto {
  /** The unique ID of the computer call. */
  id: string;
  /** The action requested for the computer call. */
  action: GPTV3ResponseComputerToolCallClickDto | GPTV3ResponseComputerToolCallDoubleClickDto | GPTV3ResponseComputerToolCallDragDto | GPTV3ResponseComputerToolCallKeypressDto | GPTV3ResponseComputerToolCallMoveDto | GPTV3ResponseComputerToolCallScreenshotDto | GPTV3ResponseComputerToolCallScrollDto | GPTV3ResponseComputerToolCallTypeDto | GPTV3ResponseComputerToolCallWaitDto;
  /** The ID of the tool call. */
  call_id: string;
  /** Pending safety checks for the computer call. */
  pending_safety_checks: GPTV3ResponseComputerToolCallPendingSafetyCheckDto[];
  status: GPTV3ResponseComputerToolCallDtoStatus;
  type: GPTV3ResponseComputerToolCallDtoType;
}
