/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseCustomToolCallOutputDtoType } from './gPTV3ResponseCustomToolCallOutputDtoType';

export interface GPTV3ResponseCustomToolCallOutputDto {
  call_id: string;
  /** JSON string result from your custom tool. */
  output: string;
  type: GPTV3ResponseCustomToolCallOutputDtoType;
  id?: string;
}
