/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseComputerToolCallMoveDtoType = typeof GPTV3ResponseComputerToolCallMoveDtoType[keyof typeof GPTV3ResponseComputerToolCallMoveDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseComputerToolCallMoveDtoType = {
  move: 'move',
} as const;
