/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface GPTV3ResponseComputerToolCallPendingSafetyCheckDto {
  id: string;
  code: string;
  message: string;
}
