/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The status of the image generation call.
 */
export type GPTV3ResponseOutputItemImageGenerationCallDtoStatus = typeof GPTV3ResponseOutputItemImageGenerationCallDtoStatus[keyof typeof GPTV3ResponseOutputItemImageGenerationCallDtoStatus];


export const GPTV3ResponseOutputItemImageGenerationCallDtoStatus = {
  in_progress: 'in_progress',
  completed: 'completed',
  generating: 'generating',
  failed: 'failed',
} as const;
