/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseInputFunctionCallOutputDtoStatus } from './gPTV3ResponseInputFunctionCallOutputDtoStatus';
import type { GPTV3ResponseInputFunctionCallOutputDtoType } from './gPTV3ResponseInputFunctionCallOutputDtoType';

export interface GPTV3ResponseInputFunctionCallOutputDto {
  call_id: string;
  /** JSON string result from your function. */
  output: string;
  type: GPTV3ResponseInputFunctionCallOutputDtoType;
  /** @nullable */
  id?: string | null;
  status?: GPTV3ResponseInputFunctionCallOutputDtoStatus;
}
