/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3UserMessageDtoContentOneOfItem } from './gPTV3UserMessageDtoContentOneOfItem';

/**
 * The content of the user message. Can be a string or an array of text and image inputs.
 */
export type GPTV3UserMessageDtoContent = string | GPTV3UserMessageDtoContentOneOfItem[];
