/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3FileSearchToolDto } from './gPTV3FileSearchToolDto';
import type { GPTV3FunctionToolDto } from './gPTV3FunctionToolDto';
import type { GPTV3ImageGenerationToolDto } from './gPTV3ImageGenerationToolDto';
import type { GPTV3InputModel } from './gPTV3InputModel';
import type { GPTV3InputToolChoice } from './gPTV3InputToolChoice';
import type { GPTV3ResponseCodeInterpreterToolCallDto } from './gPTV3ResponseCodeInterpreterToolCallDto';
import type { GPTV3ResponseComputerToolCallDto } from './gPTV3ResponseComputerToolCallDto';
import type { GPTV3ResponseCustomToolCallDto } from './gPTV3ResponseCustomToolCallDto';
import type { GPTV3ResponseCustomToolCallOutputDto } from './gPTV3ResponseCustomToolCallOutputDto';
import type { GPTV3ResponseFileSearchToolCallDto } from './gPTV3ResponseFileSearchToolCallDto';
import type { GPTV3ResponseFunctionToolCallDto } from './gPTV3ResponseFunctionToolCallDto';
import type { GPTV3ResponseFunctionWebSearchDto } from './gPTV3ResponseFunctionWebSearchDto';
import type { GPTV3ResponseInputComputerCallOutputDto } from './gPTV3ResponseInputComputerCallOutputDto';
import type { GPTV3ResponseInputFunctionCallOutputDto } from './gPTV3ResponseInputFunctionCallOutputDto';
import type { GPTV3ResponseInputItemImageGenerationCallDto } from './gPTV3ResponseInputItemImageGenerationCallDto';
import type { GPTV3ResponseInputItemMessage } from './gPTV3ResponseInputItemMessage';
import type { GPTV3ResponseInputItemReferenceDto } from './gPTV3ResponseInputItemReferenceDto';
import type { GPTV3ResponseInputLocalShellCallDto } from './gPTV3ResponseInputLocalShellCallDto';
import type { GPTV3ResponseInputLocalShellCallOutputDto } from './gPTV3ResponseInputLocalShellCallOutputDto';
import type { GPTV3ResponseInputMcpApprovalRequestDto } from './gPTV3ResponseInputMcpApprovalRequestDto';
import type { GPTV3ResponseInputMcpApprovalResponseDto } from './gPTV3ResponseInputMcpApprovalResponseDto';
import type { GPTV3ResponseInputMcpCallDto } from './gPTV3ResponseInputMcpCallDto';
import type { GPTV3ResponseInputMcpListToolsDto } from './gPTV3ResponseInputMcpListToolsDto';
import type { GPTV3ResponseOutputMessageDto } from './gPTV3ResponseOutputMessageDto';
import type { GPTV3ResponseReasoningItemDto } from './gPTV3ResponseReasoningItemDto';
import type { GPTV3TextConfigDto } from './gPTV3TextConfigDto';
import type { GPTV3WebSearchToolDto } from './gPTV3WebSearchToolDto';

export interface GPTV3Input {
  /** ID of the model to use. See OpenAI docs for model endpoint compatibility. */
  model?: GPTV3InputModel;
  /** Text, image, or file inputs to the model, used to generate a response. Can be a simple string, a single message object, or an array of messages with different roles. */
  input?: string | (GPTV3ResponseInputItemMessage | GPTV3ResponseOutputMessageDto | GPTV3ResponseFileSearchToolCallDto | GPTV3ResponseComputerToolCallDto | GPTV3ResponseInputComputerCallOutputDto | GPTV3ResponseFunctionWebSearchDto | GPTV3ResponseFunctionToolCallDto | GPTV3ResponseInputFunctionCallOutputDto | GPTV3ResponseReasoningItemDto | GPTV3ResponseInputItemImageGenerationCallDto | GPTV3ResponseCodeInterpreterToolCallDto | GPTV3ResponseInputLocalShellCallDto | GPTV3ResponseInputLocalShellCallOutputDto | GPTV3ResponseInputMcpListToolsDto | GPTV3ResponseInputMcpApprovalRequestDto | GPTV3ResponseInputMcpApprovalResponseDto | GPTV3ResponseInputMcpCallDto | GPTV3ResponseCustomToolCallOutputDto | GPTV3ResponseCustomToolCallDto | GPTV3ResponseInputItemReferenceDto)[];
  /** Configuration options for a text response from the model. Can be plain text or structured JSON data. */
  text?: GPTV3TextConfigDto;
  /** This feature is in Beta. If specified, OpenAI will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result. */
  seed?: number;
  /** A list of tools the model may call. Supports function, file_search, web_search_preview, and image_generation tools. */
  tools?: (GPTV3FunctionToolDto | GPTV3FileSearchToolDto | GPTV3WebSearchToolDto | GPTV3ImageGenerationToolDto)[];
  /** Controls how the model chooses tools: "none" disables, "auto" lets the model decide, "required" forces a tool call, or specify an explicit tool choice. */
  tool_choice?: GPTV3InputToolChoice;
  /** Maximum number of output tokens to generate. */
  max_output_tokens?: number;
  /** Specifies which additional data to include in the response. For file search, use ["file_search_call.results"] to include search results. */
  include?: string[];
}
