/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The role of the message sender.
 */
export type GPTV3ResponseInputItemMessageRole = typeof GPTV3ResponseInputItemMessageRole[keyof typeof GPTV3ResponseInputItemMessageRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseInputItemMessageRole = {
  user: 'user',
  system: 'system',
  developer: 'developer',
} as const;
