/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseCodeInterpreterToolCallDtoType = typeof GPTV3ResponseCodeInterpreterToolCallDtoType[keyof typeof GPTV3ResponseCodeInterpreterToolCallDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseCodeInterpreterToolCallDtoType = {
  code_interpreter_call: 'code_interpreter_call',
} as const;
