/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseInputComputerCallOutputDtoType = typeof GPTV3ResponseInputComputerCallOutputDtoType[keyof typeof GPTV3ResponseInputComputerCallOutputDtoType];


export const GPTV3ResponseInputComputerCallOutputDtoType = {
  computer_call_output: 'computer_call_output',
} as const;
