/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseOutputMessageDtoRole } from './gPTV3ResponseOutputMessageDtoRole';
import type { GPTV3ResponseOutputMessageDtoStatus } from './gPTV3ResponseOutputMessageDtoStatus';
import type { GPTV3ResponseOutputMessageDtoType } from './gPTV3ResponseOutputMessageDtoType';
import type { GPTV3ResponseOutputRefusalDto } from './gPTV3ResponseOutputRefusalDto';
import type { GPTV3ResponseOutputTextDto } from './gPTV3ResponseOutputTextDto';

export interface GPTV3ResponseOutputMessageDto {
  /** The unique identifier for the message. */
  id: string;
  /** The type of the message. This is the SECOND output item when file_search or web_search tool is called, containing the model response with citations. */
  type: GPTV3ResponseOutputMessageDtoType;
  /** The role of the message sender. */
  role: GPTV3ResponseOutputMessageDtoRole;
  /** The content of the message with annotations and citations. */
  content: (GPTV3ResponseOutputTextDto | GPTV3ResponseOutputRefusalDto)[];
  status: GPTV3ResponseOutputMessageDtoStatus;
}
