/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseLocalShellCallDtoType = typeof GPTV3ResponseLocalShellCallDtoType[keyof typeof GPTV3ResponseLocalShellCallDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseLocalShellCallDtoType = {
  local_shell_call: 'local_shell_call',
} as const;
