/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Ranking options for the search.
 * @nullable
 */
export type GPTV3FileSearchToolDtoRanking = { [key: string]: unknown } | null;
