/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Environment variables map.
 */
export type GPTV3ResponseLocalShellCallActionDtoEnv = { [key: string]: unknown };
