/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of the tool call.
 */
export type GPTV3ResponseCustomToolCallDtoType = typeof GPTV3ResponseCustomToolCallDtoType[keyof typeof GPTV3ResponseCustomToolCallDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseCustomToolCallDtoType = {
  custom_tool_call: 'custom_tool_call',
} as const;
