/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseOutputTextContainerFileCitationDtoType = typeof GPTV3ResponseOutputTextContainerFileCitationDtoType[keyof typeof GPTV3ResponseOutputTextContainerFileCitationDtoType];


export const GPTV3ResponseOutputTextContainerFileCitationDtoType = {
  container_file_citation: 'container_file_citation',
} as const;
