/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3WebSearchCallDtoType } from './gPTV3WebSearchCallDtoType';

export interface GPTV3WebSearchCallDto {
  /** The unique identifier for this tool call. */
  id: string;
  /** The type of tool call: web_search_preview. */
  type: GPTV3WebSearchCallDtoType;
}
