/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The quality level for image generation.
 */
export type GPTV3ImageGenerationToolDtoQuality = typeof GPTV3ImageGenerationToolDtoQuality[keyof typeof GPTV3ImageGenerationToolDtoQuality];


export const GPTV3ImageGenerationToolDtoQuality = {
  auto: 'auto',
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;
