/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseComputerToolCallClickDto } from './gPTV3ResponseComputerToolCallClickDto';
import type { GPTV3ResponseComputerToolCallDoubleClickDto } from './gPTV3ResponseComputerToolCallDoubleClickDto';
import type { GPTV3ResponseComputerToolCallDragDto } from './gPTV3ResponseComputerToolCallDragDto';
import type { GPTV3ResponseComputerToolCallKeypressDto } from './gPTV3ResponseComputerToolCallKeypressDto';
import type { GPTV3ResponseComputerToolCallMoveDto } from './gPTV3ResponseComputerToolCallMoveDto';
import type { GPTV3ResponseComputerToolCallScreenshotDto } from './gPTV3ResponseComputerToolCallScreenshotDto';
import type { GPTV3ResponseComputerToolCallScrollDto } from './gPTV3ResponseComputerToolCallScrollDto';
import type { GPTV3ResponseComputerToolCallTypeDto } from './gPTV3ResponseComputerToolCallTypeDto';
import type { GPTV3ResponseComputerToolCallWaitDto } from './gPTV3ResponseComputerToolCallWaitDto';

/**
 * The action requested for the computer call.
 */
export type GPTV3ResponseComputerToolCallDtoAction = GPTV3ResponseComputerToolCallClickDto | GPTV3ResponseComputerToolCallDoubleClickDto | GPTV3ResponseComputerToolCallDragDto | GPTV3ResponseComputerToolCallKeypressDto | GPTV3ResponseComputerToolCallMoveDto | GPTV3ResponseComputerToolCallScreenshotDto | GPTV3ResponseComputerToolCallScrollDto | GPTV3ResponseComputerToolCallTypeDto | GPTV3ResponseComputerToolCallWaitDto;
