/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseCodeInterpreterToolCallLogsDtoType = typeof GPTV3ResponseCodeInterpreterToolCallLogsDtoType[keyof typeof GPTV3ResponseCodeInterpreterToolCallLogsDtoType];


export const GPTV3ResponseCodeInterpreterToolCallLogsDtoType = {
  logs: 'logs',
} as const;
