/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseInputMcpListToolsToolDtoAnnotations } from './gPTV3ResponseInputMcpListToolsToolDtoAnnotations';
import type { GPTV3ResponseInputMcpListToolsToolDtoInputSchema } from './gPTV3ResponseInputMcpListToolsToolDtoInputSchema';

export interface GPTV3ResponseInputMcpListToolsToolDto {
  input_schema: GPTV3ResponseInputMcpListToolsToolDtoInputSchema;
  name: string;
  /** @nullable */
  annotations?: GPTV3ResponseInputMcpListToolsToolDtoAnnotations;
  /** @nullable */
  description?: string | null;
}
