/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseFormatJsonSchemaDto } from './gPTV3ResponseFormatJsonSchemaDto';
import type { GPTV3ResponseFormatTextDto } from './gPTV3ResponseFormatTextDto';

export interface GPTV3TextConfigDto {
  /** The format for the text response. */
  format?: GPTV3ResponseFormatTextDto | GPTV3ResponseFormatJsonSchemaDto;
}
