/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of the tool.
 */
export type GPTV3WebSearchToolDtoType = typeof GPTV3WebSearchToolDtoType[keyof typeof GPTV3WebSearchToolDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3WebSearchToolDtoType = {
  web_search_preview: 'web_search_preview',
} as const;
