/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseFileSearchToolCallDtoType } from './gPTV3ResponseFileSearchToolCallDtoType';
import type { GPTV3ResponseFileSearchToolCallDtoStatus } from './gPTV3ResponseFileSearchToolCallDtoStatus';
import type { GPTV3ResponseFileSearchToolCallResultDto } from './gPTV3ResponseFileSearchToolCallResultDto';

export interface GPTV3ResponseFileSearchToolCallDto {
  /** The type of the file search result. This is the FIRST output item when file_search tool is called. */
  type: GPTV3ResponseFileSearchToolCallDtoType;
  /** The unique identifier for this file search call. */
  id: string;
  /** The status of the file search call. */
  status: GPTV3ResponseFileSearchToolCallDtoStatus;
  /** The search queries used for the file search. */
  queries: string[];
  /**
   * The search results from the file search. Can be null if no results found.
   * @nullable
   */
  results?: GPTV3ResponseFileSearchToolCallResultDto[] | null;
}
