/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseMcpCallDtoType = typeof GPTV3ResponseMcpCallDtoType[keyof typeof GPTV3ResponseMcpCallDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseMcpCallDtoType = {
  mcp_call: 'mcp_call',
} as const;
