/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseInputFunctionCallOutputDtoStatus = typeof GPTV3ResponseInputFunctionCallOutputDtoStatus[keyof typeof GPTV3ResponseInputFunctionCallOutputDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseInputFunctionCallOutputDtoStatus = {
  in_progress: 'in_progress',
  completed: 'completed',
  incomplete: 'incomplete',
} as const;
