/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseMcpApprovalRequestDtoType = typeof GPTV3ResponseMcpApprovalRequestDtoType[keyof typeof GPTV3ResponseMcpApprovalRequestDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseMcpApprovalRequestDtoType = {
  mcp_approval_request: 'mcp_approval_request',
} as const;
