/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of content.
 */
export type GPTV3ResponseOutputRefusalDtoType = typeof GPTV3ResponseOutputRefusalDtoType[keyof typeof GPTV3ResponseOutputRefusalDtoType];


export const GPTV3ResponseOutputRefusalDtoType = {
  refusal: 'refusal',
} as const;
