/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of response format being defined: 'text' or 'json_object'.
 */
export type GPTV2ResponseFormatTextOrObjectDtoType = typeof GPTV2ResponseFormatTextOrObjectDtoType[keyof typeof GPTV2ResponseFormatTextOrObjectDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV2ResponseFormatTextOrObjectDtoType = {
  text: 'text',
  json_object: 'json_object',
} as const;
