/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseCodeInterpreterToolCallImageDtoType } from './gPTV3ResponseCodeInterpreterToolCallImageDtoType';

export interface GPTV3ResponseCodeInterpreterToolCallImageDto {
  type: GPTV3ResponseCodeInterpreterToolCallImageDtoType;
  url: string;
}
