/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ToolChoiceDtoType } from './gPTV3ToolChoiceDtoType';
import type { GPTV3ToolChoiceFunctionDto } from './gPTV3ToolChoiceFunctionDto';

export interface GPTV3ToolChoiceDto {
  /** Controls which (if any) tool is called by the model. 'none', 'auto', 'required', or a specific tool type. */
  type: GPTV3ToolChoiceDtoType;
  /** The function to call, if type is `function`. */
  function?: GPTV3ToolChoiceFunctionDto;
}
