/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ContentWithAnnotationsDtoType } from './gPTV3ContentWithAnnotationsDtoType';
import type { GPTV3AnnotationDto } from './gPTV3AnnotationDto';

export interface GPTV3ContentWithAnnotationsDto {
  /** The type of content. */
  type: GPTV3ContentWithAnnotationsDtoType;
  /** The text content. */
  text: string;
  /** Annotations for the content. */
  annotations?: GPTV3AnnotationDto[];
}
