/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV2ResponseFormatTextOrObjectDtoType } from './gPTV2ResponseFormatTextOrObjectDtoType';

export interface GPTV2ResponseFormatTextOrObjectDto {
  /** The type of response format being defined: 'text' or 'json_object'. */
  type: GPTV2ResponseFormatTextOrObjectDtoType;
}
