/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ImageInputDto } from './gPTV3ImageInputDto';
import type { GPTV3ResponseInputItemMessageRole } from './gPTV3ResponseInputItemMessageRole';
import type { GPTV3ResponseInputItemMessageStatus } from './gPTV3ResponseInputItemMessageStatus';
import type { GPTV3ResponseInputItemMessageType } from './gPTV3ResponseInputItemMessageType';
import type { GPTV3TextInputDto } from './gPTV3TextInputDto';

export interface GPTV3ResponseInputItemMessage {
  /** A list of input items (text, image, file). */
  content: (GPTV3TextInputDto | GPTV3ImageInputDto)[];
  /** The role of the message sender. */
  role: GPTV3ResponseInputItemMessageRole;
  /** The type of the message input. Always message. */
  type?: GPTV3ResponseInputItemMessageType;
  status?: GPTV3ResponseInputItemMessageStatus;
}
