/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseInputLocalShellCallDtoType = typeof GPTV3ResponseInputLocalShellCallDtoType[keyof typeof GPTV3ResponseInputLocalShellCallDtoType];


export const GPTV3ResponseInputLocalShellCallDtoType = {
  local_shell_call: 'local_shell_call',
} as const;
