/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseComputerToolCallDragDtoType } from './gPTV3ResponseComputerToolCallDragDtoType';
import type { GPTV3ResponseComputerToolCallDragPathDto } from './gPTV3ResponseComputerToolCallDragPathDto';

export interface GPTV3ResponseComputerToolCallDragDto {
  type: GPTV3ResponseComputerToolCallDragDtoType;
  path: GPTV3ResponseComputerToolCallDragPathDto[];
}
