/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3AssistantMessageDtoContentOneOfItem } from './gPTV3AssistantMessageDtoContentOneOfItem';

/**
 * The content of the assistant message. Can be a string or an array of text and image inputs.
 */
export type GPTV3AssistantMessageDtoContent = string | GPTV3AssistantMessageDtoContentOneOfItem[];
