/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseOutputTextURLCitationDtoType = typeof GPTV3ResponseOutputTextURLCitationDtoType[keyof typeof GPTV3ResponseOutputTextURLCitationDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseOutputTextURLCitationDtoType = {
  url_citation: 'url_citation',
} as const;
