/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GptV2ResponseKind } from './gptV2ResponseKind';
import type { OperationOutputJSON } from './operationOutputJSON';
import type { GptV2ResponseInput } from './gptV2ResponseInput';
import type { GptV2ResponseStatus } from './gptV2ResponseStatus';
import type { GptV2ResponseMetadata } from './gptV2ResponseMetadata';

export interface GptV2Response {
  kind: GptV2ResponseKind;
  output: OperationOutputJSON;
  input: GptV2ResponseInput;
  status: GptV2ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: GptV2ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
