/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseOutputTextDtoType } from './gPTV3ResponseOutputTextDtoType';
import type { GPTV3ResponseOutputTextDtoAnnotationsItem } from './gPTV3ResponseOutputTextDtoAnnotationsItem';
import type { GPTV3ResponseOutputTextLogprobDto } from './gPTV3ResponseOutputTextLogprobDto';

export interface GPTV3ResponseOutputTextDto {
  /** The type of content. */
  type: GPTV3ResponseOutputTextDtoType;
  /** The text content. */
  text: string;
  /** Annotations attached to spans of the output text (citations, file paths, etc). */
  annotations: GPTV3ResponseOutputTextDtoAnnotationsItem[];
  /** Log probabilities for tokens (when requested). */
  logprobs?: GPTV3ResponseOutputTextLogprobDto[];
}
