/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseInputLocalShellCallOutputDtoType } from './gPTV3ResponseInputLocalShellCallOutputDtoType';
import type { GPTV3ResponseInputLocalShellCallOutputDtoStatus } from './gPTV3ResponseInputLocalShellCallOutputDtoStatus';

export interface GPTV3ResponseInputLocalShellCallOutputDto {
  id: string;
  /** JSON string result from the local shell call. */
  output: string;
  type: GPTV3ResponseInputLocalShellCallOutputDtoType;
  status?: GPTV3ResponseInputLocalShellCallOutputDtoStatus;
}
