/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV2DeveloperMessageDtoRole } from './gPTV2DeveloperMessageDtoRole';

export interface GPTV2DeveloperMessageDto {
  /** The content of the developer message. */
  content: string;
  /** The role of the message sender. */
  role: GPTV2DeveloperMessageDtoRole;
  /** The name of the sender, if applicable. */
  name?: string;
}
