/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseInputMcpApprovalRequestDtoType = typeof GPTV3ResponseInputMcpApprovalRequestDtoType[keyof typeof GPTV3ResponseInputMcpApprovalRequestDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseInputMcpApprovalRequestDtoType = {
  mcp_approval_request: 'mcp_approval_request',
} as const;
