/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV2MessageToolCallDtoFunction } from './gPTV2MessageToolCallDtoFunction';
import type { GPTV2MessageToolCallDtoType } from './gPTV2MessageToolCallDtoType';

export interface GPTV2MessageToolCallDto {
  id: string;
  function: GPTV2MessageToolCallDtoFunction;
  type: GPTV2MessageToolCallDtoType;
}
