/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of the web search result. This is the FIRST output item when web_search tool is called.
 */
export type GPTV3ResponseFunctionWebSearchDtoType = typeof GPTV3ResponseFunctionWebSearchDtoType[keyof typeof GPTV3ResponseFunctionWebSearchDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseFunctionWebSearchDtoType = {
  web_search_call: 'web_search_call',
} as const;
