/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3FileSearchResultsDto } from './gPTV3FileSearchResultsDto';

/**
 * The search results from the file search. Can be null if no results found.
 * @nullable
 */
export type GPTV3FileSearchResultDtoSearchResults = GPTV3FileSearchResultsDto | null;
