/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseOutputTextContainerFileCitationDto } from './gPTV3ResponseOutputTextContainerFileCitationDto';
import type { GPTV3ResponseOutputTextDtoType } from './gPTV3ResponseOutputTextDtoType';
import type { GPTV3ResponseOutputTextFileCitationDto } from './gPTV3ResponseOutputTextFileCitationDto';
import type { GPTV3ResponseOutputTextFilePathDto } from './gPTV3ResponseOutputTextFilePathDto';
import type { GPTV3ResponseOutputTextLogprobDto } from './gPTV3ResponseOutputTextLogprobDto';
import type { GPTV3ResponseOutputTextURLCitationDto } from './gPTV3ResponseOutputTextURLCitationDto';

export interface GPTV3ResponseOutputTextDto {
  /** The type of content. */
  type: GPTV3ResponseOutputTextDtoType;
  /** The text content. */
  text: string;
  /** Annotations attached to spans of the output text (citations, file paths, etc). */
  annotations: (GPTV3ResponseOutputTextFileCitationDto | GPTV3ResponseOutputTextURLCitationDto | GPTV3ResponseOutputTextContainerFileCitationDto | GPTV3ResponseOutputTextFilePathDto)[];
  /** Log probabilities for tokens (when requested). */
  logprobs?: GPTV3ResponseOutputTextLogprobDto[];
}
