/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of annotation.
 */
export type GPTV3AnnotationDtoType = typeof GPTV3AnnotationDtoType[keyof typeof GPTV3AnnotationDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3AnnotationDtoType = {
  file_citation: 'file_citation',
  url_citation: 'url_citation',
} as const;
