/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GPTV3ResponseComputerToolCallDragDtoType = typeof GPTV3ResponseComputerToolCallDragDtoType[keyof typeof GPTV3ResponseComputerToolCallDragDtoType];


export const GPTV3ResponseComputerToolCallDragDtoType = {
  drag: 'drag',
} as const;
