/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of the tool. Currently, only 'function' is supported.
 */
export type GPTV2ToolDtoType = typeof GPTV2ToolDtoType[keyof typeof GPTV2ToolDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV2ToolDtoType = {
  function: 'function',
} as const;
