/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GptV1ResponseStatus = typeof GptV1ResponseStatus[keyof typeof GptV1ResponseStatus];


export const GptV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
