/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV1InputModel } from './gPTV1InputModel';

export interface GPTV1Input {
  model?: GPTV1InputModel;
  prompt: string;
  additionalMessages?: string[];
  imageId?: string;
}
