/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * The type of response format being defined: json_schema.
 */
export type GPTV3ResponseFormatJsonSchemaDtoType = typeof GPTV3ResponseFormatJsonSchemaDtoType[keyof typeof GPTV3ResponseFormatJsonSchemaDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GPTV3ResponseFormatJsonSchemaDtoType = {
  json_schema: 'json_schema',
} as const;
