/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { GPTV3ResponseComputerToolCallWaitDtoType } from './gPTV3ResponseComputerToolCallWaitDtoType';

export interface GPTV3ResponseComputerToolCallWaitDto {
  type: GPTV3ResponseComputerToolCallWaitDtoType;
}
