/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GrantAccessControllerParamsPrincipalType = typeof GrantAccessControllerParamsPrincipalType[keyof typeof GrantAccessControllerParamsPrincipalType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GrantAccessControllerParamsPrincipalType = {
  account: 'account',
  group: 'group',
} as const;
