/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type GrantAccessControllerParamsPrincipalType = typeof GrantAccessControllerParamsPrincipalType[keyof typeof GrantAccessControllerParamsPrincipalType];


export const GrantAccessControllerParamsPrincipalType = {
  account: 'account',
  group: 'group',
} as const;
