/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { NaomiPrepareDatasetInputDto } from './naomiPrepareDatasetInputDto';
import type { HauteNaomiPrepareDatasetV1RequestMetadata } from './hauteNaomiPrepareDatasetV1RequestMetadata';

export interface HauteNaomiPrepareDatasetV1Request {
  input: NaomiPrepareDatasetInputDto;
  metadata?: HauteNaomiPrepareDatasetV1RequestMetadata;
}
