/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type HauteLindaV1ResponseKind = typeof HauteLindaV1ResponseKind[keyof typeof HauteLindaV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HauteLindaV1ResponseKind = {
  operation: 'operation',
} as const;
