/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { HauteNaomiV1ResponseKind } from './hauteNaomiV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { HauteNaomiV1ResponseInput } from './hauteNaomiV1ResponseInput';
import type { HauteNaomiV1ResponseStatus } from './hauteNaomiV1ResponseStatus';
import type { HauteNaomiV1ResponseMetadata } from './hauteNaomiV1ResponseMetadata';

export interface HauteNaomiV1Response {
  kind: HauteNaomiV1ResponseKind;
  output: OperationOutputImageSingle;
  input: HauteNaomiV1ResponseInput;
  status: HauteNaomiV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: HauteNaomiV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
