/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type HauteLindaV1ResponseStatus = typeof HauteLindaV1ResponseStatus[keyof typeof HauteLindaV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HauteLindaV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
