/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { HauteLindaV1ResponseKind } from './hauteLindaV1ResponseKind';
import type { OperationOutputImageMultiple } from './operationOutputImageMultiple';
import type { HauteLindaV1ResponseInput } from './hauteLindaV1ResponseInput';
import type { HauteLindaV1ResponseStatus } from './hauteLindaV1ResponseStatus';
import type { HauteLindaV1ResponseMetadata } from './hauteLindaV1ResponseMetadata';

export interface HauteLindaV1Response {
  kind: HauteLindaV1ResponseKind;
  output: OperationOutputImageMultiple;
  input: HauteLindaV1ResponseInput;
  status: HauteLindaV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: HauteLindaV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
