/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type HauteNaomiTrainV1ResponseKind = typeof HauteNaomiTrainV1ResponseKind[keyof typeof HauteNaomiTrainV1ResponseKind];


export const HauteNaomiTrainV1ResponseKind = {
  operation: 'operation',
} as const;
