/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type HauteNaomiTrainV1ResponseKind = typeof HauteNaomiTrainV1ResponseKind[keyof typeof HauteNaomiTrainV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HauteNaomiTrainV1ResponseKind = {
  operation: 'operation',
} as const;
