/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type HauteNaomiPrepareDatasetV1ResponseStatus = typeof HauteNaomiPrepareDatasetV1ResponseStatus[keyof typeof HauteNaomiPrepareDatasetV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HauteNaomiPrepareDatasetV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
