/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type HauteNaomiTrainV1ResponseStatus = typeof HauteNaomiTrainV1ResponseStatus[keyof typeof HauteNaomiTrainV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HauteNaomiTrainV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
