/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { HauteNaomiTrainV1ResponseKind } from './hauteNaomiTrainV1ResponseKind';
import type { NaomiHauteTrainOutputDto } from './naomiHauteTrainOutputDto';
import type { HauteNaomiTrainV1ResponseInput } from './hauteNaomiTrainV1ResponseInput';
import type { HauteNaomiTrainV1ResponseStatus } from './hauteNaomiTrainV1ResponseStatus';
import type { HauteNaomiTrainV1ResponseMetadata } from './hauteNaomiTrainV1ResponseMetadata';

export interface HauteNaomiTrainV1Response {
  kind: HauteNaomiTrainV1ResponseKind;
  output: NaomiHauteTrainOutputDto;
  input: HauteNaomiTrainV1ResponseInput;
  status: HauteNaomiTrainV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: HauteNaomiTrainV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
