/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type IdeogramCharacterV1ResponseKind = typeof IdeogramCharacterV1ResponseKind[keyof typeof IdeogramCharacterV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdeogramCharacterV1ResponseKind = {
  operation: 'operation',
} as const;
