/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { IdeogramCharacterV1ResponseKind } from './ideogramCharacterV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { IdeogramCharacterV1ResponseInput } from './ideogramCharacterV1ResponseInput';
import type { IdeogramCharacterV1ResponseStatus } from './ideogramCharacterV1ResponseStatus';
import type { IdeogramCharacterV1ResponseMetadata } from './ideogramCharacterV1ResponseMetadata';

export interface IdeogramCharacterV1Response {
  kind: IdeogramCharacterV1ResponseKind;
  output: OperationOutputImageSingle;
  input: IdeogramCharacterV1ResponseInput;
  status: IdeogramCharacterV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  id: string;
  creatorId: string;
  metadata: IdeogramCharacterV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
