/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Imagen4UltraV1InputAspectRatio } from './imagen4UltraV1InputAspectRatio';

export interface Imagen4UltraV1Input {
  /** Text prompt describing the image to generate */
  prompt: string;
  /** Aspect ratio of the generated image */
  aspectRatio?: Imagen4UltraV1InputAspectRatio;
  /** Negative prompt to avoid certain elements in the image */
  negativePrompt?: string;
  /** Random seed for deterministic generation */
  seed?: number;
}
