/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ImagesDownscaleV1Input } from './imagesDownscaleV1Input';
import type { ImagesDownscaleV1RequestMetadata } from './imagesDownscaleV1RequestMetadata';

export interface ImagesDownscaleV1Request {
  input: ImagesDownscaleV1Input;
  metadata?: ImagesDownscaleV1RequestMetadata;
}
