/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ImagesRenameV1ResponseKind = typeof ImagesRenameV1ResponseKind[keyof typeof ImagesRenameV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImagesRenameV1ResponseKind = {
  operation: 'operation',
} as const;
