/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Imagen4StandardV1ResponseKind } from './imagen4StandardV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { Imagen4StandardV1ResponseInput } from './imagen4StandardV1ResponseInput';
import type { Imagen4StandardV1ResponseStatus } from './imagen4StandardV1ResponseStatus';
import type { Imagen4StandardV1ResponseMetadata } from './imagen4StandardV1ResponseMetadata';

export interface Imagen4StandardV1Response {
  kind: Imagen4StandardV1ResponseKind;
  output: OperationOutputImageSingle;
  input: Imagen4StandardV1ResponseInput;
  status: Imagen4StandardV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: Imagen4StandardV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
