/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ImagineKateV1RequestMetadata } from './imagineKateV1RequestMetadata';
import type { KateImagineV1Input } from './kateImagineV1Input';

export interface ImagineKateV1Request {
  input: KateImagineV1Input;
  metadata?: ImagineKateV1RequestMetadata;
}
