/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Imagen4InputAspectRatio = typeof Imagen4InputAspectRatio[keyof typeof Imagen4InputAspectRatio];


export const Imagen4InputAspectRatio = {
  '1:1': '1:1',
  '9:16': '9:16',
  '16:9': '16:9',
  '3:4': '3:4',
  '4:3': '4:3',
} as const;
