/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Imagen4InputAspectRatio } from './imagen4InputAspectRatio';
import type { Imagen4InputSafetyFilterLevel } from './imagen4InputSafetyFilterLevel';

export interface Imagen4Input {
  prompt: string;
  aspectRatio?: Imagen4InputAspectRatio;
  safetyFilterLevel: Imagen4InputSafetyFilterLevel;
}
