/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ImagineFlux11ProUltraV1ResponseStatus = typeof ImagineFlux11ProUltraV1ResponseStatus[keyof typeof ImagineFlux11ProUltraV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImagineFlux11ProUltraV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
