/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Imagen4FastV1ResponseKind = typeof Imagen4FastV1ResponseKind[keyof typeof Imagen4FastV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Imagen4FastV1ResponseKind = {
  operation: 'operation',
} as const;
