/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { KateImagineV1Input } from './kateImagineV1Input';
import type { ImagineKateV1RequestMetadata } from './imagineKateV1RequestMetadata';

export interface ImagineKateV1Request {
  input: KateImagineV1Input;
  metadata?: ImagineKateV1RequestMetadata;
}
