/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface ImagesDownscaleV1Input {
  imageId: string;
  /** @minimum 1 */
  maxSide: number;
}
