/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ImagesRenameV1ResponseStatus = typeof ImagesRenameV1ResponseStatus[keyof typeof ImagesRenameV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImagesRenameV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
