/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Imagen4StandardV1ResponseInput } from './imagen4StandardV1ResponseInput';
import type { Imagen4StandardV1ResponseKind } from './imagen4StandardV1ResponseKind';
import type { Imagen4StandardV1ResponseMetadata } from './imagen4StandardV1ResponseMetadata';
import type { Imagen4StandardV1ResponseStatus } from './imagen4StandardV1ResponseStatus';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';

export interface Imagen4StandardV1Response {
  kind: Imagen4StandardV1ResponseKind;
  output: OperationOutputImageSingle;
  input: Imagen4StandardV1ResponseInput;
  status: Imagen4StandardV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: Imagen4StandardV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
