/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ImagineFlux11ProUltraV1ResponseKind = typeof ImagineFlux11ProUltraV1ResponseKind[keyof typeof ImagineFlux11ProUltraV1ResponseKind];


export const ImagineFlux11ProUltraV1ResponseKind = {
  operation: 'operation',
} as const;
