/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ImagesConvertFormatV1ResponseStatus = typeof ImagesConvertFormatV1ResponseStatus[keyof typeof ImagesConvertFormatV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImagesConvertFormatV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
