/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Imagen4StandardV1Input } from './imagen4StandardV1Input';
import type { Imagen4StandardV1RequestMetadata } from './imagen4StandardV1RequestMetadata';

export interface Imagen4StandardV1Request {
  input: Imagen4StandardV1Input;
  metadata?: Imagen4StandardV1RequestMetadata;
}
