/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ImagesRenameV1ResponseStatus = typeof ImagesRenameV1ResponseStatus[keyof typeof ImagesRenameV1ResponseStatus];


export const ImagesRenameV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
