/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type InpaintKateV1ResponseKind = typeof InpaintKateV1ResponseKind[keyof typeof InpaintKateV1ResponseKind];


export const InpaintKateV1ResponseKind = {
  operation: 'operation',
} as const;
