/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { InpaintKateV1RequestMetadata } from './inpaintKateV1RequestMetadata';
import type { KateInpaintV1Input } from './kateInpaintV1Input';

export interface InpaintKateV1Request {
  input: KateInpaintV1Input;
  metadata?: InpaintKateV1RequestMetadata;
}
