/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type InpaintKateV1ResponseStatus = typeof InpaintKateV1ResponseStatus[keyof typeof InpaintKateV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InpaintKateV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
