/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type InpaintKateV1ResponseKind = typeof InpaintKateV1ResponseKind[keyof typeof InpaintKateV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InpaintKateV1ResponseKind = {
  operation: 'operation',
} as const;
