/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type InpaintKateV1ResponseStatus = typeof InpaintKateV1ResponseStatus[keyof typeof InpaintKateV1ResponseStatus];


export const InpaintKateV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
