/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type KateInpaintV1InputBranch = typeof KateInpaintV1InputBranch[keyof typeof KateInpaintV1InputBranch];


export const KateInpaintV1InputBranch = {
  stable: 'stable',
  nightly: 'nightly',
} as const;
