/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { KateImagineV1InputAspectRatio } from './kateImagineV1InputAspectRatio';

export interface KateImagineV1Input {
  aspectRatio: KateImagineV1InputAspectRatio;
  seed: number;
  prompt: string;
}
