/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { KlingVideo25TurboProImageToVideoV1ResponseInput } from './klingVideo25TurboProImageToVideoV1ResponseInput';
import type { KlingVideo25TurboProImageToVideoV1ResponseKind } from './klingVideo25TurboProImageToVideoV1ResponseKind';
import type { KlingVideo25TurboProImageToVideoV1ResponseMetadata } from './klingVideo25TurboProImageToVideoV1ResponseMetadata';
import type { KlingVideo25TurboProImageToVideoV1ResponseStatus } from './klingVideo25TurboProImageToVideoV1ResponseStatus';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';

export interface KlingVideo25TurboProImageToVideoV1Response {
  kind: KlingVideo25TurboProImageToVideoV1ResponseKind;
  output: OperationOutputVideoSingle;
  input: KlingVideo25TurboProImageToVideoV1ResponseInput;
  status: KlingVideo25TurboProImageToVideoV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: KlingVideo25TurboProImageToVideoV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
