/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { KlingVideo25ProImageToVideoV1Input } from './klingVideo25ProImageToVideoV1Input';
import type { KlingVideo25ProImageToVideoV1RequestMetadata } from './klingVideo25ProImageToVideoV1RequestMetadata';

export interface KlingVideo25ProImageToVideoV1Request {
  input: KlingVideo25ProImageToVideoV1Input;
  metadata?: KlingVideo25ProImageToVideoV1RequestMetadata;
}
