/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type KlingKolorsVtonV1ResponseStatus = typeof KlingKolorsVtonV1ResponseStatus[keyof typeof KlingKolorsVtonV1ResponseStatus];


export const KlingKolorsVtonV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
