/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type KlingVideo25ProImageToVideoV1ResponseKind = typeof KlingVideo25ProImageToVideoV1ResponseKind[keyof typeof KlingVideo25ProImageToVideoV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KlingVideo25ProImageToVideoV1ResponseKind = {
  operation: 'operation',
} as const;
