/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { KlingVideo25ProImageToVideoV1InputDuration } from './klingVideo25ProImageToVideoV1InputDuration';

export interface KlingVideo25ProImageToVideoV1Input {
  prompt: string;
  imageId: string;
  duration?: KlingVideo25ProImageToVideoV1InputDuration;
  negativePrompt?: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  cfgScale?: number;
}
