/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type KlingVideo25ProImageToVideoV1InputDuration = typeof KlingVideo25ProImageToVideoV1InputDuration[keyof typeof KlingVideo25ProImageToVideoV1InputDuration];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KlingVideo25ProImageToVideoV1InputDuration = {
  NUMBER_5: 5,
  NUMBER_10: 10,
} as const;
