/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { KlingKolorsVtonV1ResponseKind } from './klingKolorsVtonV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { KlingKolorsVtonV1ResponseInput } from './klingKolorsVtonV1ResponseInput';
import type { KlingKolorsVtonV1ResponseStatus } from './klingKolorsVtonV1ResponseStatus';
import type { KlingKolorsVtonV1ResponseMetadata } from './klingKolorsVtonV1ResponseMetadata';

export interface KlingKolorsVtonV1Response {
  kind: KlingKolorsVtonV1ResponseKind;
  output: OperationOutputImageSingle;
  input: KlingKolorsVtonV1ResponseInput;
  status: KlingKolorsVtonV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  id: string;
  creatorId: string;
  metadata: KlingKolorsVtonV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
