/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { KlingVideo25ProImageToVideoV1ResponseInput } from './klingVideo25ProImageToVideoV1ResponseInput';
import type { KlingVideo25ProImageToVideoV1ResponseKind } from './klingVideo25ProImageToVideoV1ResponseKind';
import type { KlingVideo25ProImageToVideoV1ResponseMetadata } from './klingVideo25ProImageToVideoV1ResponseMetadata';
import type { KlingVideo25ProImageToVideoV1ResponseStatus } from './klingVideo25ProImageToVideoV1ResponseStatus';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';

export interface KlingVideo25ProImageToVideoV1Response {
  kind: KlingVideo25ProImageToVideoV1ResponseKind;
  output: OperationOutputVideoSingle;
  input: KlingVideo25ProImageToVideoV1ResponseInput;
  status: KlingVideo25ProImageToVideoV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: KlingVideo25ProImageToVideoV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
