/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { LindaHauteV1InputAspectRatio } from './lindaHauteV1InputAspectRatio';

export interface LindaHauteV1Input {
  aspectRatio: LindaHauteV1InputAspectRatio;
  productImageId: string;
  prompt: string;
  seed: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  imageWeight?: number;
  negativePrompt?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  inferenceSteps?: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  guidanceScale?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  strength?: number;
}
