/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { PipelinePreviewDto } from './pipelinePreviewDto';
import type { ListPipelinesDtoPageInfo } from './listPipelinesDtoPageInfo';

export interface ListPipelinesDto {
  data: PipelinePreviewDto[];
  pageInfo: ListPipelinesDtoPageInfo;
}
