/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { CollectionEntity } from './collectionEntity';
import type { ListCollectionsDtoPageInfo } from './listCollectionsDtoPageInfo';

export interface ListCollectionsDto {
  data: CollectionEntity[];
  pageInfo: ListCollectionsDtoPageInfo;
}
