/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { StackEntity } from './stackEntity';
import type { ListStacksDtoPageInfo } from './listStacksDtoPageInfo';

export interface ListStacksDto {
  data: StackEntity[];
  pageInfo: ListStacksDtoPageInfo;
}
