/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { CollectionEntity } from './collectionEntity';
import type { PageInfoDto } from './pageInfoDto';

export interface ListCollectionsDto {
  data: CollectionEntity[];
  pageInfo: PageInfoDto;
}
