/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ResourceEntity } from './resourceEntity';
import type { ListCollectionItemsDtoPageInfo } from './listCollectionItemsDtoPageInfo';

export interface ListCollectionItemsDto {
  data: ResourceEntity[];
  pageInfo: ListCollectionItemsDtoPageInfo;
}
