/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ListPosesParamsDtoOrderBy = typeof ListPosesParamsDtoOrderBy[keyof typeof ListPosesParamsDtoOrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListPosesParamsDtoOrderBy = {
  createdAt_ASC: 'createdAt_ASC',
  createdAt_DESC: 'createdAt_DESC',
} as const;
