/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { SharedResourceDto } from './sharedResourceDto';

export interface ListSharedResourcesResponseDto {
  resources: SharedResourceDto[];
  /** @nullable */
  nextCursor?: string | null;
}
