/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { PageInfoDto } from './pageInfoDto';
import type { WorkflowDto } from './workflowDto';

export interface ListWorkflowsDto {
  data: WorkflowDto[];
  pageInfo: PageInfoDto;
}
