/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ListOperationsParamsDtoOrderBy } from './listOperationsParamsDtoOrderBy';

export interface ListOperationsParamsDto {
  orderBy?: ListOperationsParamsDtoOrderBy;
  limit?: number;
  cursor?: string;
}
