/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OperationEntity } from './operationEntity';
import type { PageInfoDto } from './pageInfoDto';

export interface ListOperationsDto {
  data: OperationEntity[];
  pageInfo: PageInfoDto;
}
