/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ListAccountsParamsDtoOrderBy } from './listAccountsParamsDtoOrderBy';

export interface ListAccountsParamsDto {
  orderBy?: ListAccountsParamsDtoOrderBy;
  limit?: number;
  ids?: string[];
  aliases?: string[];
  cursor?: string;
}
