/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { PageInfoDto } from './pageInfoDto';
import type { ResourceEntity } from './resourceEntity';

export interface ListCollectionItemsDto {
  data: ResourceEntity[];
  pageInfo: PageInfoDto;
}
