/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OperationEntity } from './operationEntity';
import type { ListOperationsDtoPageInfo } from './listOperationsDtoPageInfo';

export interface ListOperationsDto {
  data: OperationEntity[];
  pageInfo: ListOperationsDtoPageInfo;
}
