/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { StartTrainingParamsDto } from './startTrainingParamsDto';
import type { LoraTrainingRequestMetadata } from './loraTrainingRequestMetadata';

export interface LoraTrainingRequest {
  input: StartTrainingParamsDto;
  metadata?: LoraTrainingRequestMetadata;
}
