/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type LoraTrainingResponseStatus = typeof LoraTrainingResponseStatus[keyof typeof LoraTrainingResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoraTrainingResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
