/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type LoraWebhookDtoStatus = typeof LoraWebhookDtoStatus[keyof typeof LoraWebhookDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoraWebhookDtoStatus = {
  starting: 'starting',
  processing: 'processing',
  succeeded: 'succeeded',
  failed: 'failed',
  canceled: 'canceled',
} as const;
