/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type LoraTrainingOutputKind = typeof LoraTrainingOutputKind[keyof typeof LoraTrainingOutputKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoraTrainingOutputKind = {
  json: 'json',
} as const;
