/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type LoraDtoModelType = typeof LoraDtoModelType[keyof typeof LoraDtoModelType];


export const LoraDtoModelType = {
  flux: 'flux',
  naomi: 'naomi',
  custom: 'custom',
} as const;
