/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type LoraControllerGetLorasV1ModelType = typeof LoraControllerGetLorasV1ModelType[keyof typeof LoraControllerGetLorasV1ModelType];


export const LoraControllerGetLorasV1ModelType = {
  flux: 'flux',
  naomi: 'naomi',
  custom: 'custom',
} as const;
