/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type LoraTrainingResponseKind = typeof LoraTrainingResponseKind[keyof typeof LoraTrainingResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoraTrainingResponseKind = {
  operation: 'operation',
} as const;
