/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { LoraTrainingResponseKind } from './loraTrainingResponseKind';
import type { LoraTrainingOutput } from './loraTrainingOutput';
import type { LoraTrainingResponseInput } from './loraTrainingResponseInput';
import type { LoraTrainingResponseStatus } from './loraTrainingResponseStatus';
import type { LoraTrainingResponseMetadata } from './loraTrainingResponseMetadata';

export interface LoraTrainingResponse {
  kind: LoraTrainingResponseKind;
  output: LoraTrainingOutput;
  input: LoraTrainingResponseInput;
  status: LoraTrainingResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  id: string;
  creatorId: string;
  metadata: LoraTrainingResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
