/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { LumaPhotonV1InputAspectRatio } from './lumaPhotonV1InputAspectRatio';

export interface LumaPhotonV1Input {
  prompt: string;
  seed?: number;
  aspectRatio: LumaPhotonV1InputAspectRatio;
  referenceImageId?: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  imageReferenceWeight?: number;
  styleReferenceImageId?: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  styleReferenceWeight?: number;
  characterReferenceImageId?: string;
}
