/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type LumaPhotonV1InputAspectRatio = typeof LumaPhotonV1InputAspectRatio[keyof typeof LumaPhotonV1InputAspectRatio];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LumaPhotonV1InputAspectRatio = {
  '1:1': '1:1',
  '3:4': '3:4',
  '4:3': '4:3',
  '16:9': '16:9',
  '9:16': '9:16',
  '21:9': '21:9',
  '9:21': '9:21',
} as const;
