/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { LumaPhotonV1ResponseInput } from './lumaPhotonV1ResponseInput';
import type { LumaPhotonV1ResponseKind } from './lumaPhotonV1ResponseKind';
import type { LumaPhotonV1ResponseMetadata } from './lumaPhotonV1ResponseMetadata';
import type { LumaPhotonV1ResponseStatus } from './lumaPhotonV1ResponseStatus';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';

export interface LumaPhotonV1Response {
  kind: LumaPhotonV1ResponseKind;
  output: OperationOutputImageSingle;
  input: LumaPhotonV1ResponseInput;
  status: LumaPhotonV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: LumaPhotonV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
