/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type LumaPhotonV1ResponseKind = typeof LumaPhotonV1ResponseKind[keyof typeof LumaPhotonV1ResponseKind];


export const LumaPhotonV1ResponseKind = {
  operation: 'operation',
} as const;
