/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type LumaPhotonV1ResponseKind = typeof LumaPhotonV1ResponseKind[keyof typeof LumaPhotonV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LumaPhotonV1ResponseKind = {
  operation: 'operation',
} as const;
