/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type LumaPhotonV1ResponseStatus = typeof LumaPhotonV1ResponseStatus[keyof typeof LumaPhotonV1ResponseStatus];


export const LumaPhotonV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
