/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { MathV1Input } from './mathV1Input';
import type { MathV1RequestMetadata } from './mathV1RequestMetadata';

export interface MathV1Request {
  input: MathV1Input;
  metadata?: MathV1RequestMetadata;
}
