/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { MathV1ResponseKind } from './mathV1ResponseKind';
import type { OperationOutputJSON } from './operationOutputJSON';
import type { MathV1ResponseInput } from './mathV1ResponseInput';
import type { MathV1ResponseStatus } from './mathV1ResponseStatus';
import type { MathV1ResponseMetadata } from './mathV1ResponseMetadata';

export interface MathV1Response {
  kind: MathV1ResponseKind;
  output: OperationOutputJSON;
  input: MathV1ResponseInput;
  status: MathV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: MathV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
