/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { MathV1InputInput } from './mathV1InputInput';

export interface MathV1Input {
  /** Mathematical expression or JSON object with expressions to evaluate using mathjs */
  code: string;
  /** Input data for the mathematical expression */
  input?: MathV1InputInput;
}
