/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type MathV1ResponseKind = typeof MathV1ResponseKind[keyof typeof MathV1ResponseKind];


export const MathV1ResponseKind = {
  operation: 'operation',
} as const;
