/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { NaomiPrepareDatasetOutputDtoKind } from './naomiPrepareDatasetOutputDtoKind';
import type { NaomiPrepareDatasetResultDto } from './naomiPrepareDatasetResultDto';

export interface NaomiPrepareDatasetOutputDto {
  kind: NaomiPrepareDatasetOutputDtoKind;
  data: NaomiPrepareDatasetResultDto;
}
