/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { DatasetItemDto } from './datasetItemDto';

export interface NaomiPrepareDatasetInputDto {
  data: DatasetItemDto[];
  returnStream?: boolean;
}
