/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type NaomiPrepareDatasetOutputDtoKind = typeof NaomiPrepareDatasetOutputDtoKind[keyof typeof NaomiPrepareDatasetOutputDtoKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NaomiPrepareDatasetOutputDtoKind = {
  json: 'json',
} as const;
