/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { NegateImageV1Input } from './negateImageV1Input';
import type { NegateImageV1RequestMetadata } from './negateImageV1RequestMetadata';

export interface NegateImageV1Request {
  input: NegateImageV1Input;
  metadata?: NegateImageV1RequestMetadata;
}
