/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type NegateImageV1ResponseStatus = typeof NegateImageV1ResponseStatus[keyof typeof NegateImageV1ResponseStatus];


export const NegateImageV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
