/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type NegateImageV1ResponseKind = typeof NegateImageV1ResponseKind[keyof typeof NegateImageV1ResponseKind];


export const NegateImageV1ResponseKind = {
  operation: 'operation',
} as const;
