/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { NoiseV1Input } from './noiseV1Input';
import type { NoiseV1RequestMetadata } from './noiseV1RequestMetadata';

export interface NoiseV1Request {
  input: NoiseV1Input;
  metadata?: NoiseV1RequestMetadata;
}
