/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ObjectDetectionV1OutputKind } from './objectDetectionV1OutputKind';

export interface ObjectDetectionV1Output {
  kind: ObjectDetectionV1OutputKind;
  data: number[][];
}
