/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ObjectDetectionV1Input } from './objectDetectionV1Input';
import type { ObjectDetectionV1RequestMetadata } from './objectDetectionV1RequestMetadata';

export interface ObjectDetectionV1Request {
  input: ObjectDetectionV1Input;
  metadata?: ObjectDetectionV1RequestMetadata;
}
