/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ObjectDetectionV1ResponseKind } from './objectDetectionV1ResponseKind';
import type { ObjectDetectionV1Output } from './objectDetectionV1Output';
import type { ObjectDetectionV1ResponseInput } from './objectDetectionV1ResponseInput';
import type { ObjectDetectionV1ResponseStatus } from './objectDetectionV1ResponseStatus';
import type { ObjectDetectionV1ResponseMetadata } from './objectDetectionV1ResponseMetadata';

export interface ObjectDetectionV1Response {
  kind: ObjectDetectionV1ResponseKind;
  output: ObjectDetectionV1Output;
  input: ObjectDetectionV1ResponseInput;
  status: ObjectDetectionV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: ObjectDetectionV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
