/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type OnecompilerV1ResponseKind = typeof OnecompilerV1ResponseKind[keyof typeof OnecompilerV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OnecompilerV1ResponseKind = {
  operation: 'operation',
} as const;
