/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OnecompilerV1OutputKind } from './onecompilerV1OutputKind';
import type { OnecompilerV1OutputData } from './onecompilerV1OutputData';

export interface OnecompilerV1Output {
  kind: OnecompilerV1OutputKind;
  data: OnecompilerV1OutputData;
}
