/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OnecompilerV1ResponseKind } from './onecompilerV1ResponseKind';
import type { OperationOutputJSON } from './operationOutputJSON';
import type { OnecompilerV1ResponseInput } from './onecompilerV1ResponseInput';
import type { OnecompilerV1ResponseStatus } from './onecompilerV1ResponseStatus';
import type { OnecompilerV1ResponseMetadata } from './onecompilerV1ResponseMetadata';

export interface OnecompilerV1Response {
  kind: OnecompilerV1ResponseKind;
  output: OperationOutputJSON;
  input: OnecompilerV1ResponseInput;
  status: OnecompilerV1ResponseStatus;
  type: string;
  price?: string;
  id: string;
  creatorId: string;
  metadata: OnecompilerV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
