/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OnecompilerV1OutputDataResult } from './onecompilerV1OutputDataResult';

export interface OnecompilerV1OutputData {
  result?: OnecompilerV1OutputDataResult;
  /** @nullable */
  error: string | null;
}
