/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type OperationEntityStatus = typeof OperationEntityStatus[keyof typeof OperationEntityStatus];


export const OperationEntityStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
