/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Full operation object (only included if status is not pending)
 */
export type OperationStatusDtoOperation = { [key: string]: unknown };
