/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type OperationOutputImageMultipleKind = typeof OperationOutputImageMultipleKind[keyof typeof OperationOutputImageMultipleKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OperationOutputImageMultipleKind = {
  'image/multiple': 'image/multiple',
} as const;
