/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OperationOutputImageSingleKind } from './operationOutputImageSingleKind';

export interface OperationOutputImageSingle {
  kind: OperationOutputImageSingleKind;
  imageId: string;
}
