/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OperationOutputJSONDataOneOf } from './operationOutputJSONDataOneOf';

/**
 * @nullable
 */
export type OperationOutputJSONData = OperationOutputJSONDataOneOf | boolean | number | string | null;
