/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OperationOutputNumberKind } from './operationOutputNumberKind';

export interface OperationOutputNumber {
  kind: OperationOutputNumberKind;
  /** Generated number value */
  value: number;
}
