/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type PipelinesControllerListPipelinesV1Status = typeof PipelinesControllerListPipelinesV1Status[keyof typeof PipelinesControllerListPipelinesV1Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PipelinesControllerListPipelinesV1Status = {
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
} as const;
