/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type PipelinesControllerListPipelinesV1OrderBy = typeof PipelinesControllerListPipelinesV1OrderBy[keyof typeof PipelinesControllerListPipelinesV1OrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PipelinesControllerListPipelinesV1OrderBy = {
  createdAt_ASC: 'createdAt_ASC',
  createdAt_DESC: 'createdAt_DESC',
} as const;
