/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { PipelineMapV1InputInputItem } from './pipelineMapV1InputInputItem';

export interface PipelineMapV1Input {
  pipeline: string;
  /** @maxItems 100 */
  input: PipelineMapV1InputInputItem[];
  failOnError?: boolean;
}
