/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { PipelineDtoStateStatus } from './pipelineDtoStateStatus';
import type { PipelineDtoStateOutput } from './pipelineDtoStateOutput';

/**
 * State of the pipeline tasks
 */
export type PipelineDtoState = {[key: string]: {
  status?: PipelineDtoStateStatus;
  /** Output of the task */
  output?: PipelineDtoStateOutput;
}};
