/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type PipelineDtoStateStatus = typeof PipelineDtoStateStatus[keyof typeof PipelineDtoStateStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PipelineDtoStateStatus = {
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
} as const;
