/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type PipelinePreviewDtoKind = typeof PipelinePreviewDtoKind[keyof typeof PipelinePreviewDtoKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PipelinePreviewDtoKind = {
  pipeline: 'pipeline',
} as const;
