/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { PipelineMapV1ResponseKind } from './pipelineMapV1ResponseKind';
import type { OperationOutputJSON } from './operationOutputJSON';
import type { PipelineMapV1ResponseInput } from './pipelineMapV1ResponseInput';
import type { PipelineMapV1ResponseStatus } from './pipelineMapV1ResponseStatus';
import type { PipelineMapV1ResponseMetadata } from './pipelineMapV1ResponseMetadata';

export interface PipelineMapV1Response {
  kind: PipelineMapV1ResponseKind;
  output: OperationOutputJSON;
  input: PipelineMapV1ResponseInput;
  status: PipelineMapV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: PipelineMapV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
