/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { PoseEntityKind } from './poseEntityKind';
import type { ImageEntity } from './imageEntity';
import type { PoseEntityMetadata } from './poseEntityMetadata';

export interface PoseEntity {
  kind: PoseEntityKind;
  sourceImage: ImageEntity;
  previewImage?: ImageEntity;
  previewImageId?: string;
  id: string;
  creatorId: string;
  metadata: PoseEntityMetadata;
  createdAt: string;
  updatedAt: string;
}
