/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type PoseEntityKind = typeof PoseEntityKind[keyof typeof PoseEntityKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PoseEntityKind = {
  pose: 'pose',
} as const;
