/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { PoseEstimationV1OutputData } from './poseEstimationV1OutputData';
import type { PoseEstimationV1OutputKind } from './poseEstimationV1OutputKind';

export interface PoseEstimationV1Output {
  kind: PoseEstimationV1OutputKind;
  data: PoseEstimationV1OutputData;
}
