/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type PricingControllerListPricingV1OrderBy = typeof PricingControllerListPricingV1OrderBy[keyof typeof PricingControllerListPricingV1OrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PricingControllerListPricingV1OrderBy = {
  type_ASC: 'type_ASC',
  type_DESC: 'type_DESC',
} as const;
