/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type PricingControllerListPricingV1Strategy = typeof PricingControllerListPricingV1Strategy[keyof typeof PricingControllerListPricingV1Strategy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PricingControllerListPricingV1Strategy = {
  fixed: 'fixed',
  inputBased: 'inputBased',
  metricsBased: 'metricsBased',
} as const;
