/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { PublicWorkflowAccessDto } from './publicWorkflowAccessDto';
import type { PublicWorkflowDtoData } from './publicWorkflowDtoData';
import type { PublicWorkflowDtoInputSchema } from './publicWorkflowDtoInputSchema';
import type { PublicWorkflowDtoMetadata } from './publicWorkflowDtoMetadata';
import type { PublicWorkflowDtoOutputSchema } from './publicWorkflowDtoOutputSchema';
import type { PublicWorkflowDtoPipelineTemplate } from './publicWorkflowDtoPipelineTemplate';

export interface PublicWorkflowDto {
  id: string;
  alias: string;
  creatorId: string;
  /** Workflow title */
  title?: string;
  /** Workflow description */
  description?: string;
  /** Input schema for the workflow */
  inputSchema?: PublicWorkflowDtoInputSchema;
  /** Output schema for the workflow */
  outputSchema?: PublicWorkflowDtoOutputSchema;
  metadata: PublicWorkflowDtoMetadata;
  /** @nullable */
  customExecutionPrice?: string | null;
  createdAt: string;
  updatedAt: string;
  /** Indicates whether the workflow was marked as public */
  isPublic: boolean;
  latestVersionId?: string;
  latestVersionNumber?: number;
  latestPublishedAt?: string;
  data?: PublicWorkflowDtoData;
  pipelineTemplate?: PublicWorkflowDtoPipelineTemplate;
  publicAccess: PublicWorkflowAccessDto;
}
