/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Output schema for the workflow
 */
export type PublicWorkflowSummaryDtoOutputSchema = { [key: string]: unknown };
