/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { RemoveAccountFromGroupParamsDtoRole } from './removeAccountFromGroupParamsDtoRole';

export interface RemoveAccountFromGroupParamsDto {
  accountId: string;
  groupId: string;
  role: RemoveAccountFromGroupParamsDtoRole;
}
