/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { RemoveAccountFromGroupControllerParamsDtoRole } from './removeAccountFromGroupControllerParamsDtoRole';

export interface RemoveAccountFromGroupControllerParamsDto {
  accountId: string;
  role: RemoveAccountFromGroupControllerParamsDtoRole;
}
