/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type RemoveAccountFromGroupControllerParamsDtoRole = typeof RemoveAccountFromGroupControllerParamsDtoRole[keyof typeof RemoveAccountFromGroupControllerParamsDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RemoveAccountFromGroupControllerParamsDtoRole = {
  maintainer: 'maintainer',
  member: 'member',
  owner: 'owner',
} as const;
