/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ResizeV1ResponseKind } from './resizeV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { ResizeV1ResponseInput } from './resizeV1ResponseInput';
import type { ResizeV1ResponseStatus } from './resizeV1ResponseStatus';
import type { ResizeV1ResponseMetadata } from './resizeV1ResponseMetadata';

export interface ResizeV1Response {
  kind: ResizeV1ResponseKind;
  output: OperationOutputImageSingle;
  input: ResizeV1ResponseInput;
  status: ResizeV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: ResizeV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
