/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ResizeV1ResponseKind = typeof ResizeV1ResponseKind[keyof typeof ResizeV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResizeV1ResponseKind = {
  operation: 'operation',
} as const;
