/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ReveRemixV1Input } from './reveRemixV1Input';
import type { ReveRemixV1RequestMetadata } from './reveRemixV1RequestMetadata';

export interface ReveRemixV1Request {
  input: ReveRemixV1Input;
  metadata?: ReveRemixV1RequestMetadata;
}
