/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ReveRemixV1InputAspectRatio = typeof ReveRemixV1InputAspectRatio[keyof typeof ReveRemixV1InputAspectRatio];


export const ReveRemixV1InputAspectRatio = {
  '1:1': '1:1',
  '9:16': '9:16',
  '16:9': '16:9',
  '3:2': '3:2',
  '2:3': '2:3',
  '4:3': '4:3',
  '3:4': '3:4',
} as const;
