/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { ReveRemixV1ResponseInput } from './reveRemixV1ResponseInput';
import type { ReveRemixV1ResponseKind } from './reveRemixV1ResponseKind';
import type { ReveRemixV1ResponseMetadata } from './reveRemixV1ResponseMetadata';
import type { ReveRemixV1ResponseStatus } from './reveRemixV1ResponseStatus';

export interface ReveRemixV1Response {
  kind: ReveRemixV1ResponseKind;
  output: OperationOutputImageSingle;
  input: ReveRemixV1ResponseInput;
  status: ReveRemixV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: ReveRemixV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
