/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type RevokeAccessControllerParamsDtoPrincipalType = typeof RevokeAccessControllerParamsDtoPrincipalType[keyof typeof RevokeAccessControllerParamsDtoPrincipalType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RevokeAccessControllerParamsDtoPrincipalType = {
  account: 'account',
  group: 'group',
} as const;
