/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Seedream4EditV1ResponseKind = typeof Seedream4EditV1ResponseKind[keyof typeof Seedream4EditV1ResponseKind];


export const Seedream4EditV1ResponseKind = {
  operation: 'operation',
} as const;
