/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { SeedanceV1InputResolution } from './seedanceV1InputResolution';

export interface SeedanceV1Input {
  prompt?: string;
  resolution?: SeedanceV1InputResolution;
  aspectRatio?: string;
  /**
   * @minimum 2
   * @maximum 12
   */
  durationSeconds?: number;
  /**
   * @minimum -1
   * @maximum 4294967295
   */
  seed?: number;
  cameraFixed?: boolean;
  firstFrameId?: string;
  lastFrameId?: string;
}
