/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Seedream45EditV1ResponseKind = typeof Seedream45EditV1ResponseKind[keyof typeof Seedream45EditV1ResponseKind];


export const Seedream45EditV1ResponseKind = {
  operation: 'operation',
} as const;
