/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Seedream4EditV1ResponseKind = typeof Seedream4EditV1ResponseKind[keyof typeof Seedream4EditV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Seedream4EditV1ResponseKind = {
  operation: 'operation',
} as const;
