/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type SeedanceV1FastV1ResponseKind = typeof SeedanceV1FastV1ResponseKind[keyof typeof SeedanceV1FastV1ResponseKind];


export const SeedanceV1FastV1ResponseKind = {
  operation: 'operation',
} as const;
