/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Height of the generated image in pixels (2048 or 4096)
 */
export type Seedream45T2IV1InputHeight = typeof Seedream45T2IV1InputHeight[keyof typeof Seedream45T2IV1InputHeight];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Seedream45T2IV1InputHeight = {
  NUMBER_2048: 2048,
  NUMBER_4096: 4096,
} as const;
