/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type SeedV1ResponseStatus = typeof SeedV1ResponseStatus[keyof typeof SeedV1ResponseStatus];


export const SeedV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
