/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { SeedV1RequestInput } from './seedV1RequestInput';
import type { SeedV1RequestMetadata } from './seedV1RequestMetadata';

export interface SeedV1Request {
  input: SeedV1RequestInput;
  metadata?: SeedV1RequestMetadata;
}
