/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Seedream45T2IV1InputWidth } from './seedream45T2IV1InputWidth';
import type { Seedream45T2IV1InputHeight } from './seedream45T2IV1InputHeight';

export interface Seedream45T2IV1Input {
  /** Text prompt describing the image to generate. Uses BytePlus ModelArk endpoint ep-20251204195257-ptf48. */
  prompt: string;
  /** Width of the generated image in pixels (2048 or 4096) */
  width?: Seedream45T2IV1InputWidth;
  /** Height of the generated image in pixels (2048 or 4096) */
  height?: Seedream45T2IV1InputHeight;
  /** Random seed for deterministic generation */
  seed?: number;
}
