/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Seedream5LiteEditV1ResponseStatus = typeof Seedream5LiteEditV1ResponseStatus[keyof typeof Seedream5LiteEditV1ResponseStatus];


export const Seedream5LiteEditV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
