/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type SeedanceV1InputResolution = typeof SeedanceV1InputResolution[keyof typeof SeedanceV1InputResolution];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SeedanceV1InputResolution = {
  '480p': '480p',
  '720p': '720p',
  '1080p': '1080p',
} as const;
