/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type SeedanceV1LightV1ResponseKind = typeof SeedanceV1LightV1ResponseKind[keyof typeof SeedanceV1LightV1ResponseKind];


export const SeedanceV1LightV1ResponseKind = {
  operation: 'operation',
} as const;
