/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';
import type { SeedanceV1ProV1ResponseInput } from './seedanceV1ProV1ResponseInput';
import type { SeedanceV1ProV1ResponseKind } from './seedanceV1ProV1ResponseKind';
import type { SeedanceV1ProV1ResponseMetadata } from './seedanceV1ProV1ResponseMetadata';
import type { SeedanceV1ProV1ResponseStatus } from './seedanceV1ProV1ResponseStatus';

export interface SeedanceV1ProV1Response {
  kind: SeedanceV1ProV1ResponseKind;
  output: OperationOutputVideoSingle;
  input: SeedanceV1ProV1ResponseInput;
  status: SeedanceV1ProV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: SeedanceV1ProV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
