/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type SeedanceV1ProV1ResponseKind = typeof SeedanceV1ProV1ResponseKind[keyof typeof SeedanceV1ProV1ResponseKind];


export const SeedanceV1ProV1ResponseKind = {
  operation: 'operation',
} as const;
