/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Seedream4EditV1Input } from './seedream4EditV1Input';
import type { Seedream4EditV1RequestMetadata } from './seedream4EditV1RequestMetadata';

export interface Seedream4EditV1Request {
  input: Seedream4EditV1Input;
  metadata?: Seedream4EditV1RequestMetadata;
}
