/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Seedream4EditV1ResponseKind } from './seedream4EditV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { Seedream4EditV1ResponseInput } from './seedream4EditV1ResponseInput';
import type { Seedream4EditV1ResponseStatus } from './seedream4EditV1ResponseStatus';
import type { Seedream4EditV1ResponseMetadata } from './seedream4EditV1ResponseMetadata';

export interface Seedream4EditV1Response {
  kind: Seedream4EditV1ResponseKind;
  output: OperationOutputImageSingle;
  input: Seedream4EditV1ResponseInput;
  status: Seedream4EditV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  id: string;
  creatorId: string;
  metadata: Seedream4EditV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
