/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Seedream4T2iV1ResponseStatus = typeof Seedream4T2iV1ResponseStatus[keyof typeof Seedream4T2iV1ResponseStatus];


export const Seedream4T2iV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
