/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { SeedanceV1FastV1ResponseKind } from './seedanceV1FastV1ResponseKind';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';
import type { SeedanceV1FastV1ResponseInput } from './seedanceV1FastV1ResponseInput';
import type { SeedanceV1FastV1ResponseStatus } from './seedanceV1FastV1ResponseStatus';
import type { SeedanceV1FastV1ResponseMetadata } from './seedanceV1FastV1ResponseMetadata';

export interface SeedanceV1FastV1Response {
  kind: SeedanceV1FastV1ResponseKind;
  output: OperationOutputVideoSingle;
  input: SeedanceV1FastV1ResponseInput;
  status: SeedanceV1FastV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: SeedanceV1FastV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
