/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Seedream5LiteEditV1InputOptimizePromptOptions } from './seedream5LiteEditV1InputOptimizePromptOptions';

export interface Seedream5LiteEditV1Input {
  /** Text prompt describing the edit to perform. Uses BytePlus ModelArk endpoint ep-20260224233519-698zc. */
  prompt: string;
  /**
   * IDs of input images to edit
   * @minItems 1
   */
  imageIds: string[];
  /** Width of the generated image in pixels. Must satisfy: total pixels (width×height) in range [3,686,400, 9,437,184] and aspect ratio (width/height) in range [1/16, 16] */
  width?: number;
  /** Height of the generated image in pixels. Must satisfy: total pixels (width×height) in range [3,686,400, 9,437,184] and aspect ratio (width/height) in range [1/16, 16] */
  height?: number;
  /** Random seed for deterministic generation */
  seed?: number;
  /** Prompt optimization mode */
  optimizePromptOptions?: Seedream5LiteEditV1InputOptimizePromptOptions;
}
