/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Seedream3V1InputAspectRatio } from './seedream3V1InputAspectRatio';
import type { Seedream3V1InputSize } from './seedream3V1InputSize';

export interface Seedream3V1Input {
  prompt: string;
  seed?: number;
  aspectRatio: Seedream3V1InputAspectRatio;
  size: Seedream3V1InputSize;
  /**
   * @minimum 512
   * @maximum 2048
   */
  width: number;
  /**
   * @minimum 512
   * @maximum 2048
   */
  height: number;
  /**
   * @minimum 1
   * @maximum 10
   */
  guidanceScale: number;
}
