/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Seedream5LiteEditV1ResponseKind } from './seedream5LiteEditV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { Seedream5LiteEditV1ResponseInput } from './seedream5LiteEditV1ResponseInput';
import type { Seedream5LiteEditV1ResponseStatus } from './seedream5LiteEditV1ResponseStatus';
import type { Seedream5LiteEditV1ResponseMetadata } from './seedream5LiteEditV1ResponseMetadata';

export interface Seedream5LiteEditV1Response {
  kind: Seedream5LiteEditV1ResponseKind;
  output: OperationOutputImageSingle;
  input: Seedream5LiteEditV1ResponseInput;
  status: Seedream5LiteEditV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: Seedream5LiteEditV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
