/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type SeedanceV1LightV1ResponseStatus = typeof SeedanceV1LightV1ResponseStatus[keyof typeof SeedanceV1LightV1ResponseStatus];


export const SeedanceV1LightV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
