/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Prompt optimization mode
 */
export type Seedream4EditV1InputOptimizePromptOptions = typeof Seedream4EditV1InputOptimizePromptOptions[keyof typeof Seedream4EditV1InputOptimizePromptOptions];


export const Seedream4EditV1InputOptimizePromptOptions = {
  standard: 'standard',
  fast: 'fast',
} as const;
