/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Seedream45T2iV1ResponseKind } from './seedream45T2iV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { Seedream45T2iV1ResponseInput } from './seedream45T2iV1ResponseInput';
import type { Seedream45T2iV1ResponseStatus } from './seedream45T2iV1ResponseStatus';
import type { Seedream45T2iV1ResponseMetadata } from './seedream45T2iV1ResponseMetadata';

export interface Seedream45T2iV1Response {
  kind: Seedream45T2iV1ResponseKind;
  output: OperationOutputImageSingle;
  input: Seedream45T2iV1ResponseInput;
  status: Seedream45T2iV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: Seedream45T2iV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
