/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface Seedream4EditV1Input {
  prompt: string;
  /** @minItems 1 */
  imageIds: string[];
  /**
   * @minimum 1024
   * @maximum 4096
   */
  width: number;
  /**
   * @minimum 1024
   * @maximum 4096
   */
  height: number;
  seed?: number;
}
