/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Seedream4T2iV1ResponseKind = typeof Seedream4T2iV1ResponseKind[keyof typeof Seedream4T2iV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Seedream4T2iV1ResponseKind = {
  operation: 'operation',
} as const;
