/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type SeedV1ResponseStatus = typeof SeedV1ResponseStatus[keyof typeof SeedV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SeedV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
