/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Seedream45EditV1ResponseStatus = typeof Seedream45EditV1ResponseStatus[keyof typeof Seedream45EditV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Seedream45EditV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
