/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface SegmentAnythingMaskV1Input {
  imageId: string;
  box: number[];
  /**
   * @minimum 0
   * @maximum 1
   */
  smoothness?: number;
  maskThreshold?: number;
}
