/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type SegmentAnythingMaskV1ResponseKind = typeof SegmentAnythingMaskV1ResponseKind[keyof typeof SegmentAnythingMaskV1ResponseKind];


export const SegmentAnythingMaskV1ResponseKind = {
  operation: 'operation',
} as const;
