/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { SegmentAnythingEmbeddingsV1ResponseKind } from './segmentAnythingEmbeddingsV1ResponseKind';
import type { OperationOutputJSON } from './operationOutputJSON';
import type { SegmentAnythingEmbeddingsV1ResponseInput } from './segmentAnythingEmbeddingsV1ResponseInput';
import type { SegmentAnythingEmbeddingsV1ResponseStatus } from './segmentAnythingEmbeddingsV1ResponseStatus';
import type { SegmentAnythingEmbeddingsV1ResponseMetadata } from './segmentAnythingEmbeddingsV1ResponseMetadata';

export interface SegmentAnythingEmbeddingsV1Response {
  kind: SegmentAnythingEmbeddingsV1ResponseKind;
  output: OperationOutputJSON;
  input: SegmentAnythingEmbeddingsV1ResponseInput;
  status: SegmentAnythingEmbeddingsV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  id: string;
  creatorId: string;
  metadata: SegmentAnythingEmbeddingsV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
