/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { SegmentAnythingMaskV1Input } from './segmentAnythingMaskV1Input';
import type { SegmentAnythingMaskV1RequestMetadata } from './segmentAnythingMaskV1RequestMetadata';

export interface SegmentAnythingMaskV1Request {
  input: SegmentAnythingMaskV1Input;
  metadata?: SegmentAnythingMaskV1RequestMetadata;
}
