/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { SegmentAnythingMaskV1ResponseInput } from './segmentAnythingMaskV1ResponseInput';
import type { SegmentAnythingMaskV1ResponseKind } from './segmentAnythingMaskV1ResponseKind';
import type { SegmentAnythingMaskV1ResponseMetadata } from './segmentAnythingMaskV1ResponseMetadata';
import type { SegmentAnythingMaskV1ResponseStatus } from './segmentAnythingMaskV1ResponseStatus';

export interface SegmentAnythingMaskV1Response {
  kind: SegmentAnythingMaskV1ResponseKind;
  output: OperationOutputImageSingle;
  input: SegmentAnythingMaskV1ResponseInput;
  status: SegmentAnythingMaskV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: SegmentAnythingMaskV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
