/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { SelfAccountDtoPermissions } from './selfAccountDtoPermissions';
import type { SelfAccountDtoType } from './selfAccountDtoType';

export interface SelfAccountDto {
  id: string;
  alias?: string;
  permissions: SelfAccountDtoPermissions;
  balance: string;
  type: SelfAccountDtoType;
  createdAt: string;
}
