/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type SharedResourceDtoType = typeof SharedResourceDtoType[keyof typeof SharedResourceDtoType];


export const SharedResourceDtoType = {
  collection: 'collection',
  operation: 'operation',
  stack: 'stack',
  image: 'image',
  video: 'video',
  pose: 'pose',
  storage: 'storage',
  pipeline: 'pipeline',
  workflow: 'workflow',
  dataset: 'dataset',
} as const;
