/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { SharedAccessEntryDto } from './sharedAccessEntryDto';
import type { SharedAccessResponseDtoPublicAccessItem } from './sharedAccessResponseDtoPublicAccessItem';

export interface SharedAccessResponseDto {
  resourceId: string;
  entries: SharedAccessEntryDto[];
  publicAccess: SharedAccessResponseDtoPublicAccessItem[];
}
