/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { SharedAccessEntryDtoRelationsItem } from './sharedAccessEntryDtoRelationsItem';

export interface SharedAccessEntryDto {
  principalId: string;
  relations: SharedAccessEntryDtoRelationsItem[];
}
