/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type ShareWithEveryoneControllerParamsDtoAccess = typeof ShareWithEveryoneControllerParamsDtoAccess[keyof typeof ShareWithEveryoneControllerParamsDtoAccess];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShareWithEveryoneControllerParamsDtoAccess = {
  owner: 'owner',
  maintainer: 'maintainer',
  writer: 'writer',
  reader: 'reader',
  member: 'member',
  can_assign_members: 'can_assign_members',
  can_assign_maintainers: 'can_assign_maintainers',
  can_assign_owners: 'can_assign_owners',
  can_view: 'can_view',
  can_write: 'can_write',
  can_edit: 'can_edit',
  can_delete: 'can_delete',
  can_change_access: 'can_change_access',
  can_add_items: 'can_add_items',
  can_remove_items: 'can_remove_items',
  can_list: 'can_list',
  parent: 'parent',
} as const;
