/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { ShareWithEveryoneControllerParamsDtoAccessItem } from './shareWithEveryoneControllerParamsDtoAccessItem';

export interface ShareWithEveryoneControllerParamsDto {
  /** @minItems 1 */
  access: ShareWithEveryoneControllerParamsDtoAccessItem[];
}
