/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { StackEntityKind } from './stackEntityKind';
import type { StackEntityItemsItem } from './stackEntityItemsItem';
import type { StackEntityMetadata } from './stackEntityMetadata';

export interface StackEntity {
  kind: StackEntityKind;
  items: StackEntityItemsItem[];
  id: string;
  creatorId: string;
  metadata: StackEntityMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
