/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { StacksControllerListStacksV1OrderBy } from './stacksControllerListStacksV1OrderBy';

export type StacksControllerListStacksV1Params = {
orderBy?: StacksControllerListStacksV1OrderBy;
limit?: number;
cursor?: string;
};
