/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { StartNaomiTrainingParamsDtoLrScheduler } from './startNaomiTrainingParamsDtoLrScheduler';
import type { StartNaomiTrainingParamsDtoMixedPrecision } from './startNaomiTrainingParamsDtoMixedPrecision';

export interface StartNaomiTrainingParamsDto {
  modelVersion?: string;
  modelDestination?: string;
  zipFile: string;
  modelNameOrPath?: string;
  epochs?: number;
  batchSizePerDevice?: number;
  vaePath?: string;
  numWorkers?: number;
  logEvery?: number;
  ckptEvery?: number;
  maxGradNorm?: number;
  lr?: number;
  maxInputLengthLimit?: number;
  conditionDropoutProb?: number;
  adamWeightDecay?: number;
  keepRawResolution?: boolean;
  maxImageSize?: number;
  useLora?: boolean;
  loraRank?: number;
  useEma?: boolean;
  lrWarmupSteps?: number;
  reportTo?: string;
  gradientAccumulationSteps?: number;
  emaDecay?: number;
  emaPath?: string;
  useDynamicShifting?: boolean;
  lrScheduler?: StartNaomiTrainingParamsDtoLrScheduler;
  mixedPrecision?: StartNaomiTrainingParamsDtoMixedPrecision;
}
