/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { StorageRecordsResultDtoValueOneOf } from './storageRecordsResultDtoValueOneOf';

/**
 * @nullable
 */
export type StorageRecordsResultDtoValue = StorageRecordsResultDtoValueOneOf | boolean | number | string | null;
