/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type StorageEntityKind = typeof StorageEntityKind[keyof typeof StorageEntityKind];


export const StorageEntityKind = {
  storage: 'storage',
} as const;
