/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { CaseDto } from './caseDto';

export interface StringsSwitchV1Input {
  /** List of cases. Last duplicate wins. */
  cases: CaseDto[];
  /** Key to look up */
  key: string;
  /** Default value if no case matches */
  default?: string;
}
