/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { StringsSliceV1Input } from './stringsSliceV1Input';
import type { StringsSliceV1RequestMetadata } from './stringsSliceV1RequestMetadata';

export interface StringsSliceV1Request {
  input: StringsSliceV1Input;
  metadata?: StringsSliceV1RequestMetadata;
}
