/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type StringsLengthV1ResponseKind = typeof StringsLengthV1ResponseKind[keyof typeof StringsLengthV1ResponseKind];


export const StringsLengthV1ResponseKind = {
  operation: 'operation',
} as const;
