/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { StringsSwitchV1Input } from './stringsSwitchV1Input';
import type { StringsSwitchV1RequestMetadata } from './stringsSwitchV1RequestMetadata';

export interface StringsSwitchV1Request {
  input: StringsSwitchV1Input;
  metadata?: StringsSwitchV1RequestMetadata;
}
