/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type StringsSliceV1ResponseKind = typeof StringsSliceV1ResponseKind[keyof typeof StringsSliceV1ResponseKind];


export const StringsSliceV1ResponseKind = {
  operation: 'operation',
} as const;
