/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface StringsSliceV1Input {
  /** Source string to slice */
  text: string;
  /** Start index (inclusive). Negative values count from the end. */
  start?: number;
  /** End index (exclusive). Negative values count from the end. */
  end?: number;
}
