/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type StringsParseJsonV1ResponseKind = typeof StringsParseJsonV1ResponseKind[keyof typeof StringsParseJsonV1ResponseKind];


export const StringsParseJsonV1ResponseKind = {
  operation: 'operation',
} as const;
