/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type StringsTemplateV1ResponseKind = typeof StringsTemplateV1ResponseKind[keyof typeof StringsTemplateV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StringsTemplateV1ResponseKind = {
  operation: 'operation',
} as const;
