/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface StringsLengthV1Input {
  /** String to measure the length of */
  text: string;
}
