/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type StringsSliceV1ResponseKind = typeof StringsSliceV1ResponseKind[keyof typeof StringsSliceV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StringsSliceV1ResponseKind = {
  operation: 'operation',
} as const;
