/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { StringsTemplateV1Input } from './stringsTemplateV1Input';
import type { StringsTemplateV1RequestMetadata } from './stringsTemplateV1RequestMetadata';

export interface StringsTemplateV1Request {
  input: StringsTemplateV1Input;
  metadata?: StringsTemplateV1RequestMetadata;
}
