/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { StringsSwitchV1ResponseKind } from './stringsSwitchV1ResponseKind';
import type { OperationOutputTextSingle } from './operationOutputTextSingle';
import type { StringsSwitchV1ResponseInput } from './stringsSwitchV1ResponseInput';
import type { StringsSwitchV1ResponseStatus } from './stringsSwitchV1ResponseStatus';
import type { StringsSwitchV1ResponseMetadata } from './stringsSwitchV1ResponseMetadata';

export interface StringsSwitchV1Response {
  kind: StringsSwitchV1ResponseKind;
  output: OperationOutputTextSingle;
  input: StringsSwitchV1ResponseInput;
  status: StringsSwitchV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: StringsSwitchV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
