/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { TaskDtoArgsItem } from './taskDtoArgsItem';

export interface TaskDto {
  /** @nullable */
  args: TaskDtoArgsItem[] | null;
  id: string;
  method: string[];
  dependencies: string[];
  estimatedPrice: string;
}
