/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type TopazUpscaleV1InputSubjectDetection = typeof TopazUpscaleV1InputSubjectDetection[keyof typeof TopazUpscaleV1InputSubjectDetection];


export const TopazUpscaleV1InputSubjectDetection = {
  All: 'All',
  Foreground: 'Foreground',
  Background: 'Background',
} as const;
