/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { TopazUpscaleV1ResponseInput } from './topazUpscaleV1ResponseInput';
import type { TopazUpscaleV1ResponseKind } from './topazUpscaleV1ResponseKind';
import type { TopazUpscaleV1ResponseMetadata } from './topazUpscaleV1ResponseMetadata';
import type { TopazUpscaleV1ResponseStatus } from './topazUpscaleV1ResponseStatus';

export interface TopazUpscaleV1Response {
  kind: TopazUpscaleV1ResponseKind;
  output: OperationOutputImageSingle;
  input: TopazUpscaleV1ResponseInput;
  status: TopazUpscaleV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: TopazUpscaleV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
