/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type TopazUpscaleV1InputEnhanceModel = typeof TopazUpscaleV1InputEnhanceModel[keyof typeof TopazUpscaleV1InputEnhanceModel];


export const TopazUpscaleV1InputEnhanceModel = {
  Low_Resolution_V2: 'Low Resolution V2',
  Standard_V2: 'Standard V2',
  High_Fidelity_V2: 'High Fidelity V2',
  CGI: 'CGI',
  Text_Refine: 'Text Refine',
} as const;
