/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type TopazUpscaleV1InputUpscaleFactor = typeof TopazUpscaleV1InputUpscaleFactor[keyof typeof TopazUpscaleV1InputUpscaleFactor];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TopazUpscaleV1InputUpscaleFactor = {
  None: 'None',
  '2x': '2x',
  '4x': '4x',
  '6x': '6x',
} as const;
