/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type TranslateV1ResponseKind = typeof TranslateV1ResponseKind[keyof typeof TranslateV1ResponseKind];


export const TranslateV1ResponseKind = {
  operation: 'operation',
} as const;
