/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { TranslateV1OutputKind } from './translateV1OutputKind';
import type { TranslateV1OutputData } from './translateV1OutputData';

export interface TranslateV1Output {
  kind: TranslateV1OutputKind;
  data: TranslateV1OutputData;
}
