/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type TranslateV1OutputKind = typeof TranslateV1OutputKind[keyof typeof TranslateV1OutputKind];


export const TranslateV1OutputKind = {
  json: 'json',
} as const;
