/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { TranslateV1ResponseKind } from './translateV1ResponseKind';
import type { OperationOutputJSON } from './operationOutputJSON';
import type { TranslateV1ResponseInput } from './translateV1ResponseInput';
import type { TranslateV1ResponseStatus } from './translateV1ResponseStatus';
import type { TranslateV1ResponseMetadata } from './translateV1ResponseMetadata';

export interface TranslateV1Response {
  kind: TranslateV1ResponseKind;
  output: OperationOutputJSON;
  input: TranslateV1ResponseInput;
  status: TranslateV1ResponseStatus;
  type: string;
  price?: string;
  id: string;
  creatorId: string;
  metadata: TranslateV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
