/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { TranslateV1Input } from './translateV1Input';
import type { TranslateV1RequestMetadata } from './translateV1RequestMetadata';

export interface TranslateV1Request {
  input: TranslateV1Input;
  metadata?: TranslateV1RequestMetadata;
}
