/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { UpdateMetadataDtoOverwrite } from './updateMetadataDtoOverwrite';

export interface UpdateMetadataDto {
  overwrite: UpdateMetadataDtoOverwrite;
}
