/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { UpdateWorkflowParamsDtoData } from './updateWorkflowParamsDtoData';
import type { UpdateWorkflowParamsDtoMetadata } from './updateWorkflowParamsDtoMetadata';

export interface UpdateWorkflowParamsDto {
  data?: UpdateWorkflowParamsDtoData;
  version?: string;
  metadata?: UpdateWorkflowParamsDtoMetadata;
}
