/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type UploadControllerGetUploadedFileUrlV1Params = {
key: string;
base64?: boolean;
};
