/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type UpscaleV1ResponseStatus = typeof UpscaleV1ResponseStatus[keyof typeof UpscaleV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpscaleV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
