/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { UpscaleV1ResponseInput } from './upscaleV1ResponseInput';
import type { UpscaleV1ResponseKind } from './upscaleV1ResponseKind';
import type { UpscaleV1ResponseMetadata } from './upscaleV1ResponseMetadata';
import type { UpscaleV1ResponseStatus } from './upscaleV1ResponseStatus';

export interface UpscaleV1Response {
  kind: UpscaleV1ResponseKind;
  output: OperationOutputImageSingle;
  input: UpscaleV1ResponseInput;
  status: UpscaleV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: UpscaleV1ResponseMetadata;
  /** @nullable */
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}
