/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { UpscaleV1Input } from './upscaleV1Input';
import type { UpscaleV1RequestMetadata } from './upscaleV1RequestMetadata';

export interface UpscaleV1Request {
  input: UpscaleV1Input;
  metadata?: UpscaleV1RequestMetadata;
}
