/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Veo3FastV1ResponseStatus = typeof Veo3FastV1ResponseStatus[keyof typeof Veo3FastV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Veo3FastV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
