/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Video duration in seconds
 */
export type Veo31InputDuration = typeof Veo31InputDuration[keyof typeof Veo31InputDuration];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Veo31InputDuration = {
  NUMBER_4: 4,
  NUMBER_6: 6,
  NUMBER_8: 8,
} as const;
