/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Veo3V1InputAspectRatio } from './veo3V1InputAspectRatio';
import type { Veo3V1InputDuration } from './veo3V1InputDuration';
import type { Veo3V1InputResolution } from './veo3V1InputResolution';

export interface Veo3V1Input {
  /** Text prompt for video generation */
  prompt: string;
  /** Negative prompt to avoid elements */
  negativePrompt?: string;
  /** Output resolution */
  resolution?: Veo3V1InputResolution;
  /** Random seed for deterministic generation */
  seed?: number;
  /** Output aspect ratio (allowed: 16:9 or 9:16) */
  aspectRatio?: Veo3V1InputAspectRatio;
  /** Video duration in seconds */
  duration?: Veo3V1InputDuration;
  /** Image ID for first frame */
  imageId?: string;
  /** Generate audio track */
  generateAudio?: boolean;
}
