/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Output resolution
 */
export type Veo3V1InputResolution = typeof Veo3V1InputResolution[keyof typeof Veo3V1InputResolution];


export const Veo3V1InputResolution = {
  '720p': '720p',
  '1080p': '1080p',
} as const;
