/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Veo31FastV1RequestMetadata } from './veo31FastV1RequestMetadata';
import type { Veo31Input } from './veo31Input';

export interface Veo31FastV1Request {
  input: Veo31Input;
  metadata?: Veo31FastV1RequestMetadata;
}
