/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Veo3FastV1ResponseKind } from './veo3FastV1ResponseKind';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';
import type { Veo3FastV1ResponseInput } from './veo3FastV1ResponseInput';
import type { Veo3FastV1ResponseStatus } from './veo3FastV1ResponseStatus';
import type { Veo3FastV1ResponseMetadata } from './veo3FastV1ResponseMetadata';

export interface Veo3FastV1Response {
  kind: Veo3FastV1ResponseKind;
  output: OperationOutputVideoSingle;
  input: Veo3FastV1ResponseInput;
  status: Veo3FastV1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: Veo3FastV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
