/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Veo31V1ResponseKind } from './veo31V1ResponseKind';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';
import type { Veo31V1ResponseInput } from './veo31V1ResponseInput';
import type { Veo31V1ResponseStatus } from './veo31V1ResponseStatus';
import type { Veo31V1ResponseMetadata } from './veo31V1ResponseMetadata';

export interface Veo31V1Response {
  kind: Veo31V1ResponseKind;
  output: OperationOutputVideoSingle;
  input: Veo31V1ResponseInput;
  status: Veo31V1ResponseStatus;
  type: string;
  /** @nullable */
  price?: string | null;
  /** @nullable */
  estimatedPrice?: string | null;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: Veo31V1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
