/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Veo31InputAspectRatio } from './veo31InputAspectRatio';
import type { Veo31InputDuration } from './veo31InputDuration';
import type { Veo31InputResolution } from './veo31InputResolution';

export interface Veo31Input {
  /** Text prompt for video generation */
  prompt: string;
  /** Negative prompt to avoid elements */
  negativePrompt?: string;
  /** Output resolution */
  resolution?: Veo31InputResolution;
  /** Random seed for deterministic generation */
  seed?: number;
  /** Output aspect ratio */
  aspectRatio?: Veo31InputAspectRatio;
  /** Video duration in seconds */
  duration?: Veo31InputDuration;
  /** Image ID for first frame */
  imageId?: string;
  /** Generate audio track */
  generateAudio?: boolean;
  lastFrameImageId?: string;
  /**
   * @minItems 1
   * @maxItems 3
   */
  referenceImageIds?: string[];
}
