/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Output aspect ratio
 */
export type Veo31InputAspectRatio = typeof Veo31InputAspectRatio[keyof typeof Veo31InputAspectRatio];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Veo31InputAspectRatio = {
  '16:9': '16:9',
  '9:16': '9:16',
  '1:1': '1:1',
} as const;
