/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Veo3V1Input } from './veo3V1Input';
import type { Veo3V1RequestMetadata } from './veo3V1RequestMetadata';

export interface Veo3V1Request {
  input: Veo3V1Input;
  metadata?: Veo3V1RequestMetadata;
}
