/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Veo31FastV1ResponseKind } from './veo31FastV1ResponseKind';
import type { OperationOutputVideoSingle } from './operationOutputVideoSingle';
import type { Veo31FastV1ResponseInput } from './veo31FastV1ResponseInput';
import type { Veo31FastV1ResponseStatus } from './veo31FastV1ResponseStatus';
import type { Veo31FastV1ResponseMetadata } from './veo31FastV1ResponseMetadata';

export interface Veo31FastV1Response {
  kind: Veo31FastV1ResponseKind;
  output: OperationOutputVideoSingle;
  input: Veo31FastV1ResponseInput;
  status: Veo31FastV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  errorMessage?: string;
  errorCode?: string;
  id: string;
  creatorId: string;
  metadata: Veo31FastV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
