/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Veo31Input } from './veo31Input';
import type { Veo31V1RequestMetadata } from './veo31V1RequestMetadata';

export interface Veo31V1Request {
  input: Veo31Input;
  metadata?: Veo31V1RequestMetadata;
}
