/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Veo31V1ResponseKind = typeof Veo31V1ResponseKind[keyof typeof Veo31V1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Veo31V1ResponseKind = {
  operation: 'operation',
} as const;
