/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

/**
 * Video duration in seconds
 */
export type Veo3V1InputDuration = typeof Veo3V1InputDuration[keyof typeof Veo3V1InputDuration];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Veo3V1InputDuration = {
  NUMBER_4: 4,
  NUMBER_6: 6,
  NUMBER_8: 8,
} as const;
