/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { VtonGiseleV1ResponseKind } from './vtonGiseleV1ResponseKind';
import type { OperationOutputImageSingle } from './operationOutputImageSingle';
import type { VtonGiseleV1ResponseInput } from './vtonGiseleV1ResponseInput';
import type { VtonGiseleV1ResponseStatus } from './vtonGiseleV1ResponseStatus';
import type { VtonGiseleV1ResponseMetadata } from './vtonGiseleV1ResponseMetadata';

export interface VtonGiseleV1Response {
  kind: VtonGiseleV1ResponseKind;
  output: OperationOutputImageSingle;
  input: VtonGiseleV1ResponseInput;
  status: VtonGiseleV1ResponseStatus;
  type: string;
  price?: string;
  estimatedPrice?: string;
  id: string;
  creatorId: string;
  metadata: VtonGiseleV1ResponseMetadata;
  createdAt: string;
  updatedAt: string;
}
