/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type WorkflowsRunV1ResponseKind = typeof WorkflowsRunV1ResponseKind[keyof typeof WorkflowsRunV1ResponseKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkflowsRunV1ResponseKind = {
  operation: 'operation',
} as const;
