/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export interface WorkflowStatisticsDto {
  /** Total number of pipeline runs triggered by this workflow */
  totalRuns: number;
  /** Number of successfully completed runs */
  completedRuns: number;
  /** Number of failed runs */
  failedRuns: number;
}
