/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type WorkflowsControllerListWorkflowsV1OrderBy = typeof WorkflowsControllerListWorkflowsV1OrderBy[keyof typeof WorkflowsControllerListWorkflowsV1OrderBy];


export const WorkflowsControllerListWorkflowsV1OrderBy = {
  createdAt_ASC: 'createdAt_ASC',
  createdAt_DESC: 'createdAt_DESC',
  updatedAt_ASC: 'updatedAt_ASC',
  updatedAt_DESC: 'updatedAt_DESC',
} as const;
