/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Yolo11xPoseV1OutputKind } from './yolo11xPoseV1OutputKind';

export interface Yolo11xPoseV1Output {
  kind: Yolo11xPoseV1OutputKind;
  /** Array of detected poses with keypoint coordinates */
  data: number[][][];
}
