/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */

export type Yolo11xPoseV1ResponseStatus = typeof Yolo11xPoseV1ResponseStatus[keyof typeof Yolo11xPoseV1ResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Yolo11xPoseV1ResponseStatus = {
  pending: 'pending',
  finished: 'finished',
  failed: 'failed',
} as const;
