/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import type { Yolo11xPoseV1Input } from './yolo11xPoseV1Input';
import type { Yolo11xPoseV1RequestMetadata } from './yolo11xPoseV1RequestMetadata';

export interface Yolo11xPoseV1Request {
  input: Yolo11xPoseV1Input;
  metadata?: Yolo11xPoseV1RequestMetadata;
}
