/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * directory-api
 * OpenAPI spec version: none
 */

export interface CreateUserProfileDto {
  externalId: string;
  name: string;
  /**
   * @nullable
   * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email?: string | null;
  /** @nullable */
  pictureUrl?: string | null;
}
