/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * directory-api
 * OpenAPI spec version: none
 */

export interface PublicUserProfileDto {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  externalId: string;
  handle: string;
  name: string;
  /** @nullable */
  pictureUrl?: string | null;
}
