/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * directory-api
 * OpenAPI spec version: none
 */

export interface UpdateUserProfileDto {
  handle?: string;
  name?: string;
  /** @nullable */
  pictureUrl?: string | null;
}
