import { describe, it, expect, beforeAll } from 'vitest';
import { createTestSdk } from '../test-utils';
import path from 'path';
import { ShareWithEveryoneControllerParamsDtoAccessItem } from '../../autogenerated/schemas';

describe('Access E2E - currentAccess', () => {
    const sdk = createTestSdk();

    it('should get current user access for a resource', async () => {
        const imageEntity = await sdk.images.createFromFile(path.join(__dirname, 'assets', 'pose.png'));

        const currentAccess = await sdk.access.currentAccess(imageEntity.id);
        expect(currentAccess).toBeDefined();
        expect(currentAccess).toHaveProperty('resourceId');
        expect(currentAccess.resourceId).toBe(imageEntity.id);
        expect(currentAccess).toHaveProperty('relations');
        expect(Array.isArray(currentAccess.relations)).toBe(true);
    });
});

describe('Access E2E - listSharedUsers', () => {
    const sdk = createTestSdk();

    it('should get list of users with access to a resource', async () => {
        const imageEntity = await sdk.images.createFromFile(path.join(__dirname, 'assets', 'pose.png'));

        const sharedUsers = await sdk.access.listSharedUsers(imageEntity.id);
        expect(sharedUsers).toBeDefined();
        expect(Array.isArray(sharedUsers)).toBe(true);
    });

    it('should return shared users with correct structure', async () => {
        const imageEntity = await sdk.images.createFromFile(path.join(__dirname, 'assets', 'pose.png'));

        const sharedUsers = await sdk.access.listSharedUsers(imageEntity.id);
        if (sharedUsers.length > 0) {
            const entry = sharedUsers[0];
            expect(entry).toHaveProperty('resourceId');
            expect(entry).toHaveProperty('principalId');
            expect(entry).toHaveProperty('relations');
            expect(Array.isArray(entry.relations)).toBe(true);
        }
    });
});

describe('Access E2E - listShared', () => {
    const sdk = createTestSdk();

    it('should return a list structure (resources array)', async () => {
        const res = await sdk.access.listShared();
        // Basic shape assertions
        expect(res).toBeDefined();
        expect(res).toHaveProperty('resources');
        expect(Array.isArray(res.resources)).toBe(true);
    });

    it('should accept pagination params (limit, cursor)', async () => {
        const res = await sdk.access.listShared({ limit: 1 });
        expect(res).toBeDefined();
        expect(res).toHaveProperty('resources');
        expect(Array.isArray(res.resources)).toBe(true);
    });
});

describe('Access E2E - shareWithEveryone and revokeFromEveryone', () => {
    const sdk = createTestSdk();

    it('should share resource with everyone with public_read access', async () => {
        const imageEntity = await sdk.images.createFromFile(path.join(__dirname, 'assets', 'pose.png'));

        await expect(
            sdk.access.shareWithEveryone(imageEntity.id, {
                access: [ShareWithEveryoneControllerParamsDtoAccessItem.public_read],
            }),
        ).resolves.not.toThrow();
    });

    it('should revoke everyone access from resource', async () => {
        const imageEntity = await sdk.images.createFromFile(path.join(__dirname, 'assets', 'pose.png'));

        // First share with everyone
        await sdk.access.shareWithEveryone(imageEntity.id, {
            access: [ShareWithEveryoneControllerParamsDtoAccessItem.public_read],
        });

        // Then revoke
        await expect(sdk.access.revokeFromEveryone(imageEntity.id)).resolves.not.toThrow();
    });

    it('should handle multiple access levels for shareWithEveryone', async () => {
        const imageEntity = await sdk.images.createFromFile(path.join(__dirname, 'assets', 'pose.png'));
        const accessLevels = [
            [ShareWithEveryoneControllerParamsDtoAccessItem.public_read],
            [ShareWithEveryoneControllerParamsDtoAccessItem.public_execute],
        ];

        for (const access of accessLevels) {
            await expect(sdk.access.shareWithEveryone(imageEntity.id, { access })).resolves.not.toThrow();
        }
    });

    it('should handle multiple access levels for revokeFromEveryone', async () => {
        const imageEntity = await sdk.images.createFromFile(path.join(__dirname, 'assets', 'pose.png'));
        const accessLevels = [
            [ShareWithEveryoneControllerParamsDtoAccessItem.public_read],
            [ShareWithEveryoneControllerParamsDtoAccessItem.public_execute],
        ];

        for (const access of accessLevels) {
            // Share first
            await sdk.access.shareWithEveryone(imageEntity.id, { access });

            // Then revoke
            await expect(sdk.access.revokeFromEveryone(imageEntity.id)).resolves.not.toThrow();
        }
    });
});
