/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Hautech API
 * OpenAPI spec version: 1.0
 */
import { axiosMutator } from '../../api-utils';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getWebsocket = () => {
const websocketControllerRegisterWebsocketV1 = (
    
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/websocket/auth`, method: 'POST'
    },
      options);
    }
  const websocketControllerGetSettingsV1 = (
    
 options?: SecondParameter<typeof axiosMutator>,) => {
      return axiosMutator<void>(
      {url: `/v1/websocket/settings`, method: 'GET'
    },
      options);
    }
  return {websocketControllerRegisterWebsocketV1,websocketControllerGetSettingsV1}};
export type WebsocketControllerRegisterWebsocketV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWebsocket>['websocketControllerRegisterWebsocketV1']>>>
export type WebsocketControllerGetSettingsV1Result = NonNullable<Awaited<ReturnType<ReturnType<typeof getWebsocket>['websocketControllerGetSettingsV1']>>>
