name: Test
on:
    push:
        branches:
            - 'main'
jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        environment: main
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4


            - name: Use Node LTS
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Test
              run: pnpm test
              env:
                  API_CORE_URL: https://api.dev.hautech.ai
                  APP_ID: ${{ secrets.APP_ID }}
                  APP_KEY_ID: ${{ secrets.APP_KEY_ID }}
                  APP_KEY_SECRET: ${{ secrets.APP_KEY_SECRET }}
                  SDK_TOKEN: ${{ secrets.SDK_TOKEN }}
